### ISSUE TITLE
DialTLS() not working for me

### ISSUE THREAD

**Issue by flimzy** [go-ldap/ldap#11]
I may be using DialTLS() wrong, but it doesn't work for me.

Consider this simple script:

    package main

    import (
        "fmt"
        "crypto/tls"
        "github.com/go-ldap/ldap"
    )

    func main() {
        conn,err := ldap.DialTLS("tcp","173.9.229.241:389",&tls.Config{InsecureSkipVerify:true})
        fmt.Printf("conn: %s\nerr: %s\n", conn,err)
    }

Which outputs:

> Connected? false
> err: LDAP Result Code 200 "": read tcp 173.9.229.241:389: connection reset by peer

However, if I change it to call StartTLS after the connection is established, it works:

    package main

    import (
        "fmt"
        "crypto/tls"
        "github.com/go-ldap/ldap"
    )

    func main() {
        conn,_ := ldap.Dial("tcp","173.9.229.241:389")
        err := conn.StartTLS(&tls.Config{InsecureSkipVerify:true})
        fmt.Printf("Connected? %t\nerr: %s\n", conn != nil, err)
    }

> Connected? true  
> err: %!s(<nil>)

Am I using DialTLS() incorrectly?

**Comment by johnweldon** [comment]
Hmm; In my code using ldap.v0 I was using [DialTLS](https://github.com/johnweldon/go/blob/master/cmd/go-ask-ldap/go-ask-ldap.go#L165-L172), but I'm vaguely recalling that StartTLS is the correct approach now.  

cref: https://github.com/go-ldap/ldap/commit/aa6eb3f10b3a85c90ebfae57591e301fcae6d834, https://github.com/go-ldap/ldap/commit/1f1118ff00744680f29b6f9908dc9ae9e1892bd7, https://github.com/go-ldap/ldap/commit/aaa8ee7ec7f2c2e9aab8298d450ad1d8e0e49490

**Comment by flimzy** [comment]
Then I won't worry too much about getting DialTLS to work. :)

Is there support for SSL connections, too? When I try either DialTLS or StartTLS on a server configured to accept SSL connections (on port 636), I'm currently getting network timeouts.

**Comment by hochhaus** [comment]
In case it is helpful, I am able to use DialTLS on port 636 over a TLS encrypted connection without issue.

**Comment by liggitt** [comment]
DialTLS is for servers which support SSL/TLS (e.g. the connection is encrypted from the very beginning)

StartTLS is for servers which support upgrading to a TLS connection after the initial connect

**Comment by flimzy** [comment]
Yes, I realize that @liggitt. And DialTLS doesn't work for me.

**Comment by liggitt** [comment]
DialTLS and StartTLS will not both work against the same port. If StartTLS is working against port 389 (which is typical), I would not expect DialTLS to work on that port.

DialTLS is working for me against a correctly configured server. Are you able to use a standalone tool (like openssl) against your server to verify it is listening with TLS correctly?
```
openssl s_client -connect yourhost:636
```

**Comment by flimzy** [comment]
Thanks for the follow up. Unfortunately, I'm no longer working on that project (in fact, I've changed employers entirely), so am not really able to investigate this further. If this means you need to close the issue, I understand.
