### ISSUE TITLE
GSSAPI support

### ISSUE THREAD

**Issue by styleex** [go-ldap/ldap#115]
In my application i have a `/etc/krb.conf` and `/etc/krb5.keytab` (configured by `adcli join`). It would be great if this ldap library could authenticate with this credentials as python ldap3 library.

**Comment by styleex** [comment]
Do you have any thoughts about the task? Or a workaround?

**Comment by johnweldon** [comment]
I'm not familiar with using GSSAPI. If you're able to provide some more details on what an implementation might look like, it may increase the possibility of someone adding support.

**Comment by liggitt** [comment]
Typically it requires building with cgo against c-bindings to a native library. I wouldn't expect it to be built into this library, but I'd consider an interface that allowed injecting a GSSAPI provider impl.

**Comment by styleex** [comment]
@vm86 describe, please, the integration of gssapi and ldap.

 @liggitt Yes, I understand that you do not want to depend on cgo. In my opinion, the interface for implementing its authorization methods is the best option.

**Comment by vm86** [comment]
Hello, for the work of authorization it is necessary to implement the SASL
https://tools.ietf.org/html/rfc4513#section-5.2 
after that this is RFC for GSSAPI ( kerberos )
https://tools.ietf.org/html/rfc4752

if necessary, I can write more details for GSSAPI. but first need a working SASL.

**Comment by simmel** [comment]
https://github.com/apcera/gssapi might help? ⛽️ 🔥 😜

**Comment by johnweldon** [comment]
Feel free to propose an interface to expose for third party implementations

**Comment by simmel** [comment]
As I'm not-really-a-Go-programmer what does that mean?

**Comment by johnweldon** [comment]
@simmel - my suggestion wasn't directed at your proposal directly - just more generally.  The big picture response is that to practically implement GSSAPI would probably mean using C bindings, which we're not willing to do now.  If someone wants to build a third party library that wraps this one and adds GSSAPI, then we can discuss what interface/code changes are needed (if any) in this library to facilitate that.

**Comment by 29x10** [comment]
@johnweldon 

https://sourcegraph.com/github.com/python-ldap/python-ldap/-/blob/Modules/LDAPObject.c#L797:13

**Comment by johnweldon** [comment]
Interesting @29x10 - I'll reopen this as an enhancement request and with a call for volunteer help.

**Comment by TobiasKarnat** [comment]
I need this as well for enterprise use: I wrote a program to synchronize ldap-group members with local linux group users.
As sssd with krb5 is already used, I would not need a technical user to authorize with the active directory server, but could you the computer account to authorize?!

**Comment by patryk4815** [comment]
Ticket can be closed.

Keytab and other are supported now ;) 
Ref: https://github.com/go-ldap/ldap/pull/449

Example usage:
```go
package main

import (
	"fmt"
	"github.com/go-ldap/ldap/v3"
	"github.com/go-ldap/ldap/v3/gssapi"
	"log"
	"os"
)

type LdapConfig struct {
	Protocol      string
	Server        string
	Realm         string
	Basedn        string
	KrbKeytabPath string
	KrbConfPath   string
	Fqdn          string
}

func DefaultLdapConfig() LdapConfig {
	fqdn, err := os.Hostname()
	if err != nil {
		log.Fatal(err)
	}
	return LdapConfig{
		Protocol: "ldaps",
		Server:   "ldap.example.com",
		Realm:    "EXAMPLE.COM",

		// in my freeipa server it is:
		Basedn: "cn=users,cn=accounts,dc=example,dc=com",

		KrbKeytabPath: "/etc/krb5.keytab",
		KrbConfPath:   "/etc/krb5.conf",
		Fqdn:          fqdn,
	}
}

func main() {
	cfg := DefaultLdapConfig()

	// search this uid in ldap
	// in your case put different
	searchForUID := "patryk4815"

	client, err := gssapi.NewClientWithKeytab(
		"host/"+cfg.Fqdn,
		cfg.Realm,
		cfg.KrbKeytabPath,
		cfg.KrbConfPath,
	)
	if err != nil {
		log.Fatal("gssapi.NewClientWithKeytab", err)
	}
	defer client.Close()

	if err := client.Login(); err != nil {
		log.Fatal("client.Login", err)
	}

	conn, err := ldap.DialURL(fmt.Sprintf("%s://%s", cfg.Protocol, cfg.Server))
	if err != nil {
		log.Fatal("ldap.DialURL", err)
	}
	defer conn.Close()

	err = conn.GSSAPIBind(client, "ldap/"+cfg.Server, "")
	if err != nil {
		log.Fatal("conn.GSSAPIBind", err)
	}

	searchRequest := ldap.NewSearchRequest(
		cfg.Basedn,
		ldap.ScopeSingleLevel,
		ldap.NeverDerefAliases,
		1,
		0,
		false,
		fmt.Sprintf("(uid=%s)", ldap.EscapeFilter(searchForUID)),
		nil,
		nil,
	)

	searchResult, err := conn.Search(searchRequest)
	if err != nil {
		log.Fatal("conn.Search", err)
	}

	searchResult.PrettyPrint(2)
}
```
