### ISSUE TITLE
FilterExtensibleMatch not being parsed correctly

### ISSUE THREAD

**Issue by korylprince** [go-ldap/ldap#12]
It doesn't look like compiling a filter using extensibleMatch is working. For example: (UserAccountControl:1.2.840.113556.1.4.803:=2)

**Comment by johnweldon** [comment]
Thanks @korylprince - I will try to look at this in the next few weeks - feel free to poke around and make a pull request :)

**Comment by korylprince** [comment]
I did take a look at the code, but do not have the knowledge at this point to write a fix.

Once I get some time I may read some docs on the asn1-ber format and ldap. Do you have any good resources?

**Comment by liggitt** [comment]
Fixed by https://github.com/go-ldap/ldap/pull/43

**Comment by liggitt** [comment]
Tagged in https://github.com/go-ldap/ldap/releases/tag/v2.2
