### ISSUE TITLE
Expose the isClosing method from Conn

### ISSUE THREAD

**Issue by Toinews** [go-ldap/ldap#121]
Hey,

Would it be possible to expose the isClosing method from the Connection package ? 
I'm running a service and inside I use (and reuse) a connection to an LDAP but at some point the TLS connection closed and I need to know if I can reuse it. 
Right now I'm checking the error string but this is not the best way to achieve it I guess.

Thanks,

**Comment by liggitt** [comment]
A typed error could be possible, but not exporting isClosing. See discussion in https://github.com/go-ldap/ldap/issues/96

**Comment by Toinews** [comment]
Thanks ! Didn't think about the corner case in #96 . I'll write a wrapper function that will retry on ErrorNetwork. :)
