### ISSUE TITLE
Code mentions a BSD license

### ISSUE THREAD

**Issue by aviau** [go-ldap/ldap#122]
Hello!

The code mentions a BSD license:

```
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```

The BSD license says:
```
* Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
```

However, the LICENSE file was changed in https://github.com/go-ldap/ldap/commit/8ad9ef0b2b96065ece466337f14734f62db0349a

Please respect the license terms.

**Comment by liggitt** [comment]
Thanks for reporting the discrepancy. The original repo relicensed under MIT in https://github.com/mmitton/ldap/commit/9031c63a92b917c423331f055304e168d8f28789 and this was an update to match. Will open a PR to update the references from other files.
