### ISSUE TITLE
Possibility to make Conn.start exported?

### ISSUE THREAD

**Issue by wolf0403** [go-ldap/ldap#13]
Now it is possible to create new ldap.Conn with NewConn instead of Dial / DialTLS, but there is no way to call .start() on the created ldap.Conn object making NewConn not much useful.

**Comment by hochhaus** [comment]
Additionally, it is not possible to set the isTLS field on the connection returned from NewConn(). I'll send a PR shortly for these issues.

**Comment by hochhaus** [comment]
Thanks for merging. This bug can now be closed.
