### ISSUE TITLE
Is client safe for concurrency?

### ISSUE THREAD

**Issue by cjellick** [go-ldap/ldap#130]
In other words, can I use it safely from multiple goroutines?
Couldn't find this in the documentation anywhere.

**Comment by vetinari** [comment]
There's a pending one (#112) which, once fixed, makes it safe to use **but**:

LDAP itself is asynchronous, which means you can send some requests (with ascending message id) and the responses are not guaranteed to return in that order.

The code receiving the response from the server ignores any id not sent by itself which means you could send request 1 from one go routine which takes a while to complete, then send the fast request 2 from a different go routine. The second one may be picked up by the first receiver and is discarded. See https://github.com/go-ldap/ldap/blob/95ede1266b237bf8e9aa5dce0b3250e51bfefe66/conn_test.go#L63 and example output https://travis-ci.org/go-ldap/ldap/jobs/227891683#L206 (the `Received unexpected message` lines).
