### ISSUE TITLE
How to iterate through the paged results?

### ISSUE THREAD

**Issue by cemremengu** [go-ldap/ldap#131]
The LDAP server I am trying to access is limited to 1000 users per query. I can get around this using the paged result but how do I iterate through the pages? Any examples?

**Comment by johnweldon** [comment]
We don't have an example of this yet (it'd be cool if someone did this... hint hint)

Here is the RFC describing the mechanism: https://www.ietf.org/rfc/rfc2696.txt

The control structures are available, we just haven't documented using it.

**Comment by liggitt** [comment]
SearchWithPaging will iterate and accumulate the results for you, or you can do it yourself, using SearchWithPaging as an example: https://github.com/go-ldap/ldap/blob/master/search.go#L306
