### ISSUE TITLE
superfluous leading zeros when encode integer by ber

### ISSUE THREAD

**Issue by ilylia** [go-ldap/ldap#132]
`encodeInteger` will return `\x00\xa2` when `i = 162`, and this may cause a `superfluous leading zeros in length` error.

**Comment by liggitt** [comment]
thanks for the report, but this actually looks correct to me. 162 in 2's complement requires a minimum of nine bits to represent (positive numbers must have a leading zero), so it actually requires two bytes (`00000000 10100010`) or (0x00 0xa2).

what system were you working with that was complaining about this encoding?

**Comment by ilylia** [comment]
thanks for the response. 
i use the standard golang library `encoding/asn1`, and the error will occur in func `parseTagAndLength` at file [`asn1.go:521`.](https://github.com/golang/go/blob/5476967b1a3d29fef4061999c00cadbec19ac0e3/src/encoding/asn1/asn1.go#L521)
please check.

**Comment by johnweldon** [comment]
Please provide a small test case to demonstrate this bug
