### ISSUE TITLE
Can't bind to AD

### ISSUE THREAD

**Issue by vnn198** [go-ldap/ldap#138]
i'm try bind to AD Windows Server 2008 R2 and every time have error "LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580" . If im try connect to ldap.forumsys.com bind command work perfect. login and password is work too. I'm read about "secure" flag for correct connect to windows ldap, but in the documentdtion i can't finad anything about this flag. May any can help me?
ps: code example - https://play.golang.org/p/MTdlmi1dtW

**Comment by vnn198** [comment]
Bind work with another method write format
Bind("read-only-admin@example.com", "password")

**Comment by javadmohebbi** [comment]
> Bind work with another method write format
> Bind("[read-only-admin@example.com](mailto:read-only-admin@example.com)", "password")
Hi @vnn198 
Both form `user@domain.com` and `username` result the same error `LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C09042F, comment: AcceptSecurityContext error, data 52e, v2580`
