### ISSUE TITLE
v2_maintenance branch

### ISSUE THREAD

**Issue by the4thamigo-uk** [go-ldap/ldap#140]
Hi, is the HEAD of the v2_maintenance branch considered stable/release code? We would like to capture the fix in the commit below, but we are running v2.5.0 and we want to make sure we have a stable version of the library.

https://github.com/go-ldap/ldap/commit/72bdde10cebe46b8ca177665f365f12b93b08f40

Thanks

Andy

**Comment by liggitt** [comment]
there's actually a race condition introduced after v2.5.0 that is fixed in master. https://github.com/go-ldap/ldap/pull/141 picks the fix to the v2 branch, then we can cut v2.5.1

**Comment by liggitt** [comment]
v2.5.1 is released - https://github.com/go-ldap/ldap/releases/tag/v2.5.1

**Comment by the4thamigo-uk** [comment]
Thanks a lot for this.
