### ISSUE TITLE
Help / Issue with searching netgroups

### ISSUE THREAD

**Issue by omki2005** [go-ldap/ldap#144]
Hi
I was trying to use this library to search for netgroups on our LDAP server. To be precise, I was using grafana which internally just calls this library with an LDAP filter. I tried using the same LDAP filter as is required by ldapsearch but that doesn't work.

"(&(objectClass=nisNetgroup)(nisNetgroupTriple=\\(,%s,\\)))"

I think it has something to do with escaping the parenthesis correctly. I've tried other combinations :- 
\\\\28
\\\\u0028
\\\\U0028
\\\\\\(

Is there something I am missing here?

**Comment by liggitt** [comment]
if you run `(,foo,)` through EscapeFilter, it produces `\28,foo,\29`:
```
nisNetgroupTripleValue := fmt.Sprintf("(,%s,)", "foo")
filter := fmt.Sprintf("(&(objectClass=nisNetgroup)(nisNetgroupTriple=%s))", ldap.EscapeFilter(nisNetgroupTripleValue))
fmt.Println(filter)
fmt.Println(ldap.CompileFilter(filter))
```
