### ISSUE TITLE
Mocking LDAP for Unit Testing

### ISSUE THREAD

**Issue by DarthHater** [go-ldap/ldap#146]
Hello there!

I've loved using this lib but I've been struggling a bit with how to mock it for unit tests.

I have tried using `mockgen` and that is a no go since `Conn` is not an interface (Conn is I think the biggest thing I want to mock).

I was wondering if others have had success with other tools to mock this out, or if there were plans to add Interfaces to some of the stuff to make this easier when using tools like `mockgen` etc...

Thanks again for the great work on this, btw.

**Comment by liggitt** [comment]
I'd recommend writing your code to the Client interface and mocking that

https://github.com/go-ldap/ldap/blob/master/client.go

**Comment by DarthHater** [comment]
Well, that seems reasonable! Thanks for the quick reply @liggitt lemme see how it goes.

**Comment by DarthHater** [comment]
Ok at first glance, I'm not sure how to totally approach this. Could be that I'm a dummy (total possibility). There are a few methods on Conn that Client doesn't have, such as Dial and DialTLS. This means I can mock out the stuff that's doing a search etc... (which is great), just can't really mock the connect parts (probably not the biggest deal). That sound accurate?

**Comment by liggitt** [comment]
> There are a few methods on Conn that Client doesn't have, such as Dial and DialTLS. 

Dial and DialTLS aren't on Conn, they return a Conn. Conn has Start and StartTLS, which the interface does have.

> This means I can mock out the stuff that's doing a search etc... (which is great), just can't really mock the connect parts (probably not the biggest deal). That sound accurate?

Yeah, you need a different entrypoint for setup anyway, since otherwise you'd be using a completely real connection. Make the part you want to consume take a Client interface (or a function that produces a Client interface, and inject something that calls Dial and returns the result when running for real, and something that returns your mock when running unit tests)

**Comment by DarthHater** [comment]
Right-o, that's what I was kinda figuring. Thanks for the feedback!

**Comment by DarthHater** [comment]
Got some tests working, thanks again. I was coming at this backwards, appreciate the help.

**Comment by 7wesley** [comment]
You could do something like this:

```go
type Connector interface {
	Dial(network string, addr string) (LDAPConn, error)
}

// implements connector interface
type LDAP struct {
	test bool
}

// choose between mock and real
func (l LDAP) Dial(network string, addr string) (LDAPConn, error) {
	if l.test {
		return LDAPConnMock{}, nil
	}
	return ldap.Dial(network, addr)
}

type LDAPConn interface {
	Bind(username string, password string) error
	Close()
}

// implements LDAPConn interface
type LDAPConnMock struct{}

func (c LDAPConnMock) Bind(username string, password string) error {
	return nil
}

func (c LDAPConnMock) Close() {}

func connectLDAP(ldap LDAP) {
	l, err := ldap.Dial("tcp", "host")
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()

	err = l.Bind("test", "test")
	if err != nil {
		log.Fatal(err)
	}

}

func main() {
	connectLDAP(LDAP{test: true})
}
```

Create an interface `Connector` with your connection method (let's say `Dial`) and another interface `LDAPConn` for methods you need from the ldap.Conn type. Implement `Dial` to return your LDAPConn interface, returning either `ldap.Dial` or a mock.
