### ISSUE TITLE
Password could not be changed: LDAP Result Code 2 "Protocol Error": 

### ISSUE THREAD

**Issue by liu129jun** [go-ldap/ldap#147]
package main

import (
	"gopkg.in/ldap.v2"
	"fmt"
	"log"
)

func ExampleConn_PasswordModify_admin() {
	l, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", "10.0.1.11", 389))
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()

	err = l.Bind("testadmin", "test")
	if err != nil {
		log.Fatal(err)
	}

	passwordModifyRequest := ldap.NewPasswordModifyRequest("testadmin", "test", "test2")
	_, err = l.PasswordModify(passwordModifyRequest)

	if err != nil {
		log.Fatalf("Password could not be changed: %s", err.Error())
	}
}
func main() {
	ExampleConn_PasswordModify_admin()
}

run out this error:
2018/02/07 16:14:56 Password could not be changed: LDAP Result Code 2 "Protocol Error": 0000203D: LdapErr: DSID-0C090F1B, comment: Unknown extended request OID, data 0, v2580

**Comment by OuSatoru** [comment]
see https://github.com/go-ldap/ldap/issues/106
if you are using windows AD.

**Comment by johnweldon** [comment]
If #106 does not refer to the same issue as this one we can re-open this issue.
