### ISSUE TITLE
Add dial timeout.

### ISSUE THREAD

**Issue by Nitecon** [go-ldap/ldap#15]
One critical item that is missing the ability to set a timeout during dialing.  Would it be possible to have this feature added?

**Comment by johnweldon** [comment]
@Nitecon That seems reasonable - feel free to open a pull request, but if I get a chance I'll look into it too.

**Comment by Nitecon** [comment]
thanks @johnweldon when I get some free time over the next few weeks I'll try to put some time into it.

**Comment by Nitecon** [comment]
Pull request #16 fixes this issue and uses flags to not cause breaking changes in the function params
