### ISSUE TITLE
Paginated search and  

### ISSUE THREAD

**Issue by adejoux** [go-ldap/ldap#151]
Hello,

I am trying to use paginated searches but I am still having this error:

```
LDAP Result Code 11 "Admin Limit Exceeded"
```

Here the code I am using:

``` go
	searchRequest := ldap.NewSearchRequest(
		config.LDAP.BaseDN, // The base dn to search
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		config.LDAP.Filter,             // The filter to apply
		[]string{"uid", "mail"}, // A list attributes to retrieve
		[]ldap.Control{ldap.NewControlPaging(10)},
	)

	sr, err := ldapSession.SearchWithPaging(searchRequest, 10)
	if err != nil {
		log.Fatal(err)
		return
	}
       
       for _, entry := range sr.Entries {
		uid := entry.GetAttributeValue("uid")
		mail := entry.GetAttributeValue("mail")

		fmt.Printf("%s %s\n", uid, mail)

	}
```

Maybe it's not a bug but me not understanding how to use the paginated searches. Any pointers will be appreciated.

Thanks,

Alain

**Comment by johnweldon** [comment]
This seems to be addressed in [this](https://serverfault.com/questions/357877/389-directory-server-administrative-limit-exceeded-error) question.  It appears to be a server configuration issue.
