### ISSUE TITLE
latest changes not tagged

### ISSUE THREAD

**Issue by vetinari** [go-ldap/ldap#157]
The latest changes (e.g. #149) are not tagged, so we do not get `ModifyDN()` when importing as `gopgk.in/ldap.v2`

**Comment by mrccnt** [comment]
it would be really nice to have `modifyDN()` available. are there any chances this milestone will be completed in a "near future"? until then I guess I should do a `go get ...` and the checkout the given branch via `git checkout ...`?

**Comment by johnweldon** [comment]
@vetinari maybe we need to start cherry picking some changes into the v2 branch?
