### ISSUE TITLE
Adding a User to a Group

### ISSUE THREAD

**Issue by 0paIescent** [go-ldap/ldap#158]
This is less of an issue and more of a question. If I were to add a user to a group would this be the way to go:

`
modifyRequest := ldap.NewModifyRequest("cn=GroupName,ou=orgunit,dc=domain,dc=edu")
modifyRequest.Add("member", []string{"cn=User,ou=orgunit,dc=domain,dc=edu"})
conn.Modify(modifyRequest)
`

Or would adding the "member" attribute overwrite the existing "member" attribute for the group? Also any information on removing a user from a group would be much appreciated, I'm not sure how I would go about doing it.

**Comment by vetinari** [comment]
Adding a member just adds a new member, existing ones are not touched. To remove a member from a group, you must specify the value to remove (if you pass an empty list / nil, all members are removed):
```go
req := ldap.NewModifyRequest("cn=GroupName,ou=orgunit,dc=domain,dc=edu")
req.Delete("member", []string{"cn=User,ou=orgunit,dc=domain,dc=edu"})
conn.Modify(req)
```
removes `cn=User,ou=orgunit,dc=domain,dc=edu` from the group

**Comment by 0paIescent** [comment]
Thanks so much! I thought that was the right way to do it, but just wanted to make sure before I wiped a whole group.
