### ISSUE TITLE
ber error when trying to do a simplebind with controls

### ISSUE THREAD

**Issue by zhunxun** [go-ldap/ldap#162]
![image](https://user-images.githubusercontent.com/21211135/40035499-a9e015d0-5834-11e8-8533-826e1978b3d2.png)

any question?

**Comment by zhunxun** [comment]
the right request use ldapwhoami 

![image](https://user-images.githubusercontent.com/21211135/40035687-742a16c4-5835-11e8-9c43-16c713ab754b.png)

**Comment by vetinari** [comment]
Are you sending controls with the bind call or is it just the empty list of controls? The empty list is fixed 
by https://github.com/go-ldap/ldap/commit/69cb73b01ddc3d40f2ef4c0d4e78065912630f33 but it was added after the last release... see #157 . Depending on the server an empty control list works (OpenLDAP at least) of fails (https://github.com/vjeantet/ldapserver/issues/22)

**Comment by zhunxun** [comment]
I send a simplebind with ControlBeheraPasswordPolicy but can`t receive response control

**Comment by vetinari** [comment]
should be fixed by #166

**Comment by johnweldon** [comment]
@zhunxun can you confirm this is fixed in latest code (you'll have to manually check out master since this commit isn't in a tagged release yet)
@vetinari can we tag that far forward in master without breaking the v2 api as far as you know?

**Comment by vetinari** [comment]
@johnweldon at least https://github.com/go-ldap/ldap/commit/783af35940586c7b03056f4567534acc5b29287c (Client interface change) and https://github.com/go-ldap/ldap/commit/0776dae456c9f852c74287dfa8475c16401ac9a9 (modify changes) prevent us from tagging this as a v2, the last one hit me in the LDIF code

**Comment by stefanmcshane** [comment]
Closing as stale

#280 should address
