### ISSUE TITLE
matchedDN information is lost in LDAP errors

### ISSUE THREAD

**Issue by koushik2506** [go-ldap/ldap#177]
The getLDAPResultCode function in errors.go seems to ignore the matchedDN part of an LDAP error: https://tools.ietf.org/html/rfc4511#section-4.1.9

Is there any specific reason for this? 

Would changes to parse matchedDN in getLDAPResultCode, and adding  it to a new MatchedDN field in the Error structure be the direction to add this?

Thanks,

**Comment by vetinari** [comment]
yes, that should work. If you like to do the PR, also change the `Error()` to include the MatchedDN field if it's not empty, please

**Comment by koushik2506** [comment]
Thank you. I will work on the PR. Do we add a string argument for matchedDN in the NewError function?
That would entail changing calls to NewError which is spread across. Can you suggest better ways of doing this ?
