### ISSUE TITLE
TLS Options and CRT

### ISSUE THREAD

**Issue by xXPhenomXx** [go-ldap/ldap#180]
Does this library allow the setting of TLS Options and specifying a CRT file similar to what can be done in a comparable Python library?

```
                l.protocol_version = ldap.VERSION3
                l.set_option(ldap.OPT_X_TLS_DEMAND, False)
                l.set_option(ldap.OPT_DEBUG_LEVEL, 255)
                l.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap.OPT_X_TLS_DEMAND)
                l.set_option(ldap.OPT_X_TLS_CACERTFILE, 'client3.crt')
                l.simple_bind_s(binddn, pw)
```

I am trying to connect to Active Directory via LDAP and I need the TLS handshake with the cert to allow for more advanced operations like adding users, etc...

Thanks for your help

**Comment by liggitt** [comment]
DialTLS takes a [tls.Config](https://golang.org/pkg/crypto/tls/#Config) which allows customization of all client TLS options supported by the go TLS stack.
