### ISSUE TITLE
How can I add int attribute 

### ISSUE THREAD

**Issue by itcam** [go-ldap/ldap#182]
add := ldap.NewAddRequest(user)
	add.Attribute("objectClass", []string{"top", "shadowAccount", "posixAccount", "person", "organizationalPerson", "inetOrgPerson", "inetLocalMailRecipient", "hostObject"})
	add.Attribute("uid", []string{username})
	add.Attribute("uidNumber", []string{string(uid)})

uidNumber must be int ,but the paramter 2  is []string ,how can I add it

**Comment by vetinari** [comment]
In doubt use the hammer: `[]string{fmt.Sprintf("%d", uid)}`... but there's more than one way to achieve this like `[]string{strconv.Itoa(uid)}`

**Comment by idalin** [comment]
how about a bool attribute?

**Comment by johnweldon** [comment]
According to [rfc 4517](https://docs.ldap.com/specs/rfc4517.txt) bool should be `TRUE` or `FALSE`:

```
boolStr := "FALSE"
if boolVal {
  boolStr = "TRUE"
}
add.Attribute("boolAttribute", []string{boolStr})
```

**Comment by johnweldon** [comment]
The same general approach for all the types - get the value into a string representation and pass that string in.
