### ISSUE TITLE
Release new tag

### ISSUE THREAD

**Issue by Xaroth** [go-ldap/ldap#183]
In your README you specify importing gopkg.in/ldap.v2 , however, that points to version 2.5.1, which was released in November of last year. Since then there's been a few dozen new commits, some of which fix bugs people are hitting.

Would it be possible to tag/release a new version? or are there any blockers that prevent a new version from being released?

**Comment by johnweldon** [comment]
We're going to make a push to get ldap.v3 released soon

**Comment by johnweldon** [comment]
I haven't had time to fully document and verify a new release, but I've updated the tags to allow the latest code to be retrieved via `gopkg.in/ldap.v3`
