### ISSUE TITLE
rebinding fails when LDAP server is DUO's LDAP proxy

### ISSUE THREAD

**Issue by jberkenbilt** [go-ldap/ldap#192]
I am trying to bind to the DUO LDAP proxy as an LDAP server. The code below is the example code from the go-ldap webpage using DialTLS (rather than StartTLS) and with the addition of a workaround marked with `BEGIN WORKAROUND` and `END WORKAROUND`.

The flow illustrated here is
* binding first with a bind username and password
* searching for the user we want to check
* binding again as that user to authenticate that user
* rebinding as the original bind user for continued operation

When the LDAP server is DUO's LDAP proxy, the last operation (rebinding) fails with the error `unable to read LDAP response packet: unexpected EOF`. Recreating the client connection with a new call to `DialTLS` works around this. I don't know which of the following things are true:

* There is a big in Duo's LDAP proxy -- however, other C and Java implementations of LDAP binding do not seem to have this problem as several other tools are authenticating to this proxy without any problems
* There is a bug in go-ldap itself
* The example as presented is incorrect and something akin to this workaround or other modified flow is actually required to rebind

I found this problem when I was unable to hook hashicorp vault with a DUO ldap proxy. For details, see hashicorp/vault#5658. I also intend to reach out to DUO.

```go
package main

import (
	"crypto/tls"
	"github.com/go-ldap/ldap"
	"fmt"
	"log"
)

func main() {

	// The username and password we want to check
	username := "..."
	password := "..."

	bindusername := "..."
	bindpassword := "..."

	l, err := ldap.DialTLS("tcp", fmt.Sprintf("%s:%d", "duo-ldap.example.com", 636), &tls.Config{})
	if err != nil {
		log.Fatal("1: ", err)
	}
	defer l.Close()

	// First bind with a read only user
	err = l.Bind(bindusername, bindpassword)
	if err != nil {
		log.Fatal("3: ", err)
	}

	// Search for the given username
	searchRequest := ldap.NewSearchRequest(
		"dc=example,dc=com",
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		fmt.Sprintf("(sAMAccountName=%s)", username),
		[]string{"dn"},
		nil,
	)

	sr, err := l.Search(searchRequest)
	if err != nil {
		log.Fatal("4: ", err)
	}

	if len(sr.Entries) != 1 {
		log.Fatal("User does not exist or too many entries returned")
	}

	userdn := sr.Entries[0].DN

	// Bind as the user to verify their password
	err = l.Bind(userdn, password)
	if err != nil {
		log.Fatal("6: ", err)
	}

	// BEGIN WORKAROUND
	l, err = ldap.DialTLS("tcp", fmt.Sprintf("%s:%d", "duo-ldap.example.com", 636), &tls.Config{})
	if err != nil {
		log.Fatal("6a: ", err)
	}
	defer l.Close()
	// END WORKAROUND

	// Rebind as the read only user for any further queries
	err = l.Bind(bindusername, bindpassword)
	if err != nil {
		log.Fatal("7: ", err)
	}
}
```

**Comment by vetinari** [comment]
The code itself is valid and works without issues against our AD and OpenLDAP servers (without the workaround needed)

**Comment by jberkenbilt** [comment]
@vetinari I'm sure what you're saying is true. However, other ldap implementations handle the DUO LDAP proxy without any trouble. While I have no doubt that there is a bug in the DUO LDAP proxy, I think a good client-side library should have a certain amount of resilience against buggy implementations. It's the well-known [Postel's law](https://en.wikipedia.org/wiki/Robustness_principle): "be conservative in what you do, be liberal in what you accept from others". As such, I wonder whether it would be reasonable to have some kind of retry. Certainly the example that I provided above could be enhanced by replacing the connection only in the case of the invalid EOF response, but I wonder whether there's something lower down inside the library itself that can detect this. Even if the bug is with the DUO LDAP proxy, go-ldap would be better library if it tolerated this buggy implementation. In my own open source project (qpdf), I have written a lot of code over the years to make my software appropriately handle all manner of PDF files that aren't compliant with the spec. In the PDF space, "It works with Adobe Reader" matters more than "It's compliant to the spec." In the LDAP world, I'm afraid that the fact that many other client libraries can handle this server probably matters more than whether or not the bug is in the DUO code or go-ldap.

There are two additional things I would/can try to do: 1) create an example in C using libldap that has the same flow as the above code, which is based on the example from the go-ldap website, and 2) see if there's a change inside the library that can improve handling of this.

**Comment by jberkenbilt** [comment]
After discussing the issue with DUO, it turns out that DUO's default and most secure configuration explicitly closes any connection upon a bind operation that follows a previous bind operation that required an MFA challenge. Presumably this is to preclude an attack (or mistake) in which someone binds with a user whose MFA they have access to and then rebinds to a different account without a second factor. We're still discussing the behavior with DUO, but it seems likely that the ultimate resolution is just going to be to catch the error condition and explicitly re-open the connection only in the case where it fails. If this is the conclusion we come to, then I will close this issue.

**Comment by jberkenbilt** [comment]
For the benefit of anyone else who comes across this issue, setting `allow_unlimited_binds=true` enables this bind-search-bind-bind flow to work. The DUO docs are fairly clear on what you have to do to make this safe. As such, I see no reason for a change here. Thanks!
