### ISSUE TITLE
LDAP Result Code 200 "Network Error

### ISSUE THREAD

**Issue by paddy235** [go-ldap/ldap#210]
```
LDAP Result Code 200 "Network Error": dial tcp: address ldap://ldap.eccl.qhdcl:10389: too many colons in address

```

**Comment by vetinari** [comment]
don't pass the URI, just the hostname (+port)

**Comment by codepipe** [comment]
Yes thanks a lot for this support its working for me

**Comment by cpuschma** [comment]
You may now use the URI with `DialURL` for this to work 😊

https://github.com/go-ldap/ldap/blob/898ed3e692b7df574033e6705fe44c3204cb5d5a/v3/conn.go#L204-L229
