### ISSUE TITLE
set Userpassword hash method

### ISSUE THREAD

**Issue by arrow2012** [go-ldap/ldap#218]
when I add an entry to LDAP , I use
	add := ldap.NewAddRequest(user)
add.Attribute("userPassword", []string{UserPass})
the default hash method is plaintext
![image](https://user-images.githubusercontent.com/46478986/58623543-caf80000-8300-11e9-9c1b-99ce74f895be.png)

how can I set the hash method to  SSHA
![image](https://user-images.githubusercontent.com/46478986/58623633-fed32580-8300-11e9-82e7-acfcbd1b2892.png)
![image](https://user-images.githubusercontent.com/46478986/58623651-08f52400-8301-11e9-9828-cf88557e9fb5.png)

**Comment by emsearcy** [comment]
Hi - I'm another user of go-ldap. I'd recommend using the Password Modify Extended Operation ldap.NewPasswordModifyRequest() over a TLS-encrypted connection.  This sends the password in plaintext (transport encrypted), and the *server* is responsible for the hashing using the default hashing algorithm specified on the server.

If you must do the hashing client side, you can use a combination of crypto/rand, crypto/sha1 and encoding/base64 to generate a random salt, compute the hash, base64-encode the hash plus the salt, and then just prefix the base64-encoded string with "{SSHA}". You can probably find examples online—for other languages if not for go.

**Comment by cpuschma** [comment]
For password modify operations, you should generally resort to using `NewPasswordModifyRequest `. You may need to hash your password beforehand (this depends on the type of directory server you're using):
https://github.com/go-ldap/ldap/blob/898ed3e692b7df574033e6705fe44c3204cb5d5a/v3/passwdmodify.go#L57-L80
