### ISSUE TITLE
LDAP connection will be closed even if l.Close() is not called

### ISSUE THREAD

**Issue by summerQLin** [go-ldap/ldap#23]
If connection is open for a while, I try to search something again, I got error from  https://github.com/go-ldap/ldap/blob/master/conn.go#L199 

Should I close connection everytime when search is done?

**Comment by euforia** [comment]
I'm seeing the same thing.  I feel like I'm missing something.  You find a solution?

**Comment by summerQLin** [comment]
I think probably server closed the connection if connection is open for too long. So I just open/close connection for each search.

**Comment by euforia** [comment]
same here.  i think it is a tcp timeout given that it's just doing a `Dial`

**Comment by liggitt** [comment]
The connection can be closed by the server. It is ok to hold an open connection and reuse it, but you need to add error handling to reestablish the connection if it has been closed in the meantime.
