### ISSUE TITLE
SearchWithPaging returned all entries

### ISSUE THREAD

**Issue by juliardi** [go-ldap/ldap#231]
I am trying to use SearchWithPaging to limit the result of my search, but it returned all matched entries instead of limiting it to `pagingSize`.

```go
searchRequest := ldap.NewSearchRequest(
		"DC=example,DC=com",
		ldap.ScopeWholeSubtree,
		ldap.NeverDerefAliases,
		0,
		0,
		false,
		"(objectClass=person)", // The filter to apply
                []string{}, // A list attributes to retrieve
		nil,
	)

result, err := ldapConn.SearchWithPaging(searchRequest, 10)
if err != nil {
	log.Fatal(err)
}

// this will print the amount of entries matched the filter
fmt.Println(len(result.Entries)) 
```

Am I using it correctly?

**Comment by scottyseus** [comment]
This is the expected behavior, as far as I can tell.

From the [doc](https://godoc.org/gopkg.in/ldap.v3#Conn.SearchWithPaging):

> All paged LDAP query responses will be buffered and the final result will be returned atomically.

**Comment by stefanmcshane** [comment]
Closing as @scottyseus explained correctly.
Feel free to have a look through the code and commit if you have suggestions to improve!

https://github.com/go-ldap/ldap/blob/a75d3c90289dc18b8c212eccb2330969fdfd6154/v3/search.go#L272
