### ISSUE TITLE
support for multiple servers?

### ISSUE THREAD

**Issue by gliptak** [go-ldap/ldap#234]
Some LDAP libraries (like https://docs.oracle.com/javase/jndi/tutorial/ldap/misc/url.html) allow space separated list of LDAP servers while connecting. Would similar syntax be planned for ```go-ldap```?

**Comment by stefanmcshane** [comment]
There are currently no plans for implementing this. Any ldap libraries that do implement this, usually only attempt connecting to the next server, not multiple servers from one connection.
The exposed error from DialURL should allow the user to attempt connection/reconnection upon error, or using the timeouts listed in https://github.com/go-ldap/ldap/pull/249
