### ISSUE TITLE
Cut tag for current master

### ISSUE THREAD

**Issue by jefferai** [go-ldap/ldap#240]
With the change to go.mod it would be nice if that were tagged so that we can use it in a compatible way (e.g. github.com/go-ldap/ldap/v3).

**Comment by johnweldon** [comment]
v3.1.1

**Comment by jefferai** [comment]
Apologies, I forgot that also the go.mod needs to be /v3

**Comment by jefferai** [comment]
@ncabatoff CC

**Comment by johnweldon** [comment]
@jefferai feel free to make a PR for the specific change you need.

**Comment by jefferai** [comment]
Thanks -- see https://github.com/go-ldap/ldap/pull/241

**Comment by johnweldon** [comment]
I think this has been resolved by #243

**Comment by johnweldon** [comment]
And module version v3.1.2
