### ISSUE TITLE
Help fix go.mod mess

### ISSUE THREAD

**Issue by johnweldon** [go-ldap/ldap#246]
Help wanted to try fix the go.mod mess for this library.

Issues #238, #240, #242 and related pull requests were an attempt to get the ldap library working as a go module.

It doesn't appear to have worked correctly, and I don't have a lot of time to fix this.

Any help from a go modules veteran would be appreciated!

**Comment by johnweldon** [comment]
for context

I think Go modules expect that v2 and higher are referenced with a version in the import path (github.com/go-ldap/ldap/v3 or something) in this case. (#241 was on the right track I think, but I prematurely closed it)

**Comment by johnweldon** [comment]
#241 was merged and I _think_ this fixes things.

I had to do a `go get github.com/go-ldap/ldap/v3@v3.1.3` to get the tool to find it properly though.

**Comment by stefanmcshane** [comment]
I think #241 was along the right lines, however it should have been moved into a v3 subdirectory (or branch)
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

To prevent any real breaking changes, they also suggest that we increment the version to v4. It falls out of line LDAPv3 but could prevent any further breaking changes caused by this and asn1-ber.v1

**Comment by johnweldon** [comment]
I think this is resolved.

**Comment by dtenenba** [comment]
@johnweldon I'm still having `go mod` issues, but part of the problem could be that I don't know what I am doing.

```
$ go version
go version go1.13.4 darwin/amd64
```

Here I am trying to build a project that depends on this one:

```
$ cat bla.go
package main

import (
	"crypto/tls"
	"github.com/go-ldap/ldap"
)

func main() {
 	tlsConfig := &tls.Config{InsecureSkipVerify: false}
	_, _ := ldap.DialTLS("tcp", "localhost:5555", tlsConfig)
}
$ go mod init github.com/foo/bar
go: creating new go.mod: module github.com/foo/bar
$  go build bla.go
go: finding gopkg.in/asn1-ber.v1 v1.3.1
build command-line-arguments: cannot load gopkg.in/asn1-ber.v1: cannot find module providing package gopkg.in/asn1-ber.v1
```

This is driving me crazy as it's the only LDAP library that is working for me so far. I'm not sure how I ever got it working though....Maybe by not using modules? Even that approach no longer works.

**Comment by stefanmcshane** [comment]
Try importing `go get github.com/go-ldap/ldap/v3` and make sure to remove `go get github.com/go-ldap/ldap` from your go.mod

**Comment by dtenenba** [comment]
It works! Thanks.

**Comment by slingamn** [comment]
I spent some time staring at the following error messages (I was flailing around and no longer remember how they were produced exactly):

1. gopkg.in/asn1-ber.v1: cannot find module providing package gopkg.in/asn1-ber.v1: gopkg.in/asn1-ber.v1@v1.4.1: invalid version: go.mod has non-....v1 module path "github.com/go-asn1-ber/asn1-ber" at revision v1.4.1
2. github.com/go-ldap/ldap@v3.1.4: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3

If you're seeing these, make sure your *application code* is explicitly importing `github.com/go-ldap/ldap/v3`, not the un-suffixed `github.com/go-ldap/ldap`.
