### ISSUE TITLE
Cannot authenticate to Active Directory with LDAP Channel Binding enabled (nonTLS)

### ISSUE THREAD

**Issue by trdyer** [go-ldap/ldap#255]
Hey,

While trying to bind to my AD server that has Channel Binding and LDAP Signing turned on I can no longer successfully connect.

My Bind call returns:

LDAP Result Code 8 "Strong Auth Required": 00002028: LdapErr: DSID-0C090257, comment: The server requires binds to turn on integrity checking if SSL\TLS are not already active on the connection, data 0, v2580

I am using go-ldap v3.1.5

My call to bind is

```golang	
err = conn.Bind(user.DN, password)
if err != nil {
	return nil, ParseLdapErrorMessage(err)
}
```

where user.DN and password are both strings. Is this an expected feature or should I now require TLS connections to AD?

**Comment by trdyer** [comment]
For reference: https://support.microsoft.com/en-us/help/4520412/2020-ldap-channel-binding-and-ldap-signing-requirement-for-windows

**Comment by stefanmcshane** [comment]
You can optionally bind with TLS to using go-ldap. If you are enforcing Channel Binding and LDAP Signing on your AD Server, then you will require a valid ldaps connection.
I do not believe that this is a limitation of the module, but instead will require a valid cert to bind with.

DialURL will allow you to supply the relevant Dial Options to configure this.
https://github.com/go-ldap/ldap/blob/2517798aa0227380815f7a7106a194d4c7ca3bf9/v3/conn.go#L198

**Comment by trdyer** [comment]
ahhh ok, I do allow bind with TLS which works as expected. I will look into `DialOpt`'s. Thanks
