### ISSUE TITLE
Authentication and authorization against OpenLDAP, 389DS and ApacheDS?

### ISSUE THREAD

**Issue by dan-stromberg** [go-ldap/ldap#256]
Hi folks.

Can go-ldap do authentication and authorization against OpenLDAP, 389DS and ApacheDS?

I know it /should/ work, but does it?

I'm especially interested in this in a Grafana context, but I'm told they just use go-ldap.

Thanks!

**Comment by stefanmcshane** [comment]
go-ldap implements LDAPv3 as mentioned on the Readme. This means it will work with any authentication provider that implements the standard, including Microsoft AD, OpenLDAP etc.

I have not worked with 389DS or ApacheDS, but if they implement LDAP, then this will work.

Check out the examples:
https://github.com/go-ldap/ldap/blob/a4f79d8a7cda1dcfbe9efafbd1e1621608881e93/v3/examples_test.go#L11

If you are using go-modules, `go get github.com/go-ldap/ldap/v3` to get started

**Comment by dan-stromberg** [comment]
Surely the various implementations of the LDAP protocol can be expected to have different degrees of completeness and bugginess?

If nothing else, Active Directory was created at a time when Microsoft didn't much care to test its software with other implementations of a protocol.   I think it remains to be seen if Microsoft has truly changed for the better, but I think my point is illustrated: sometimes interoperability isn't as much of a priority as most techies would like it to be.  Also, sometimes even when interop Is a priority, "stuff still happens".

Do the go-ldap developers test from time to time against some LDAP servers?  Hopefully against a few or more?

Looking at https://github.com/go-ldap/ldap/blob/a4f79d8a7cda1dcfbe9efafbd1e1621608881e93/v3/examples_test.go , I'm seeing many references to ldap.example.com - is this some sort of in-memory LDAP mockery?

Thanks. :)

**Comment by stefanmcshane** [comment]
Hi @dan-stromberg,
AD seems to be our biggest userbase so far. It's difficult to test against every given implementation of the LDAP protocol, so the best we can do is to test against a mocked LDAP request & response. 
The tests do mock LDAP responses which have been so far successful
https://github.com/go-ldap/ldap/blob/a4f79d8a7cda1dcfbe9efafbd1e1621608881e93/v3/filter_test.go

If you have available resources, or ideas to do integration testing, we are all ears and open to contributions!
