### ISSUE TITLE
Document concurrency safety

### ISSUE THREAD

**Issue by timbunce** [go-ldap/ldap#259]
In an old issue #130 from 2017 @vetinari commented that
> The code receiving the response from the server ignores any id not sent by itself which means you could send request 1 from one go routine which takes a while to complete, then send the fast request 2 from a different go routine. The second one may be picked up by the first receiver and is discarded.

Is this still true? My (rough) reading of the code suggests it's no longer true, for v3 at least, but I'd appreciate confirmation.

I couldn't find a note in the docs about this but maybe I missed it.
Would be great if one could be added or made more clear.

Including some details of best-practice around connection handling (#33, #47, #181, #197) would be a bonus!

**Comment by rfyiamcool** [comment]
+1

**Comment by vetinari** [comment]
> Is this still true? My (rough) reading of the code suggests it's no longer true, for v3 at least, but I'd appreciate confirmation.

no, it's not
