### ISSUE TITLE
Add EXTERNAL SASL TLS certificate example?

### ISSUE THREAD

**Issue by 62726164** [go-ldap/ldap#273]
I have go-ldap doing EXTERNAL SASL binds using TLS client certificates. It works great. I have an example here: https://gist.github.com/62726164/1e7f245aed08fc5af208953e51385c94

Should this sort of example be added to the existing examples file to help others quickly understand how to do this?

Also, is this comment in bind.go (line 375) always true:

`// Use ldap.DialURL("ldapi://") to connect to the Unix socket before ExternalBind.`

**Comment by johnweldon** [comment]
Yes, adding examples that demonstrate how to use the library in ways that aren't obvious is something we want.  Please feel free to make a PR with that example.

I don't know the answer to the question about needing to bind to the Unix socket before `ExternalBind` is always true.  It doesn't sound right; how would you modify that comment to make more sense? `//  If using Unix sockets, make sure to bind with ldap.DialURL("ldapi://") before using ExternalBind.` ?

**Comment by 62726164** [comment]
OK, thanks. I submitted a pull request to add the example. I seldom do PRs, so I'm not sure it is correct. If not, let me know and I'll redo it.

I think your wording to modify the ExternalBind comment is ideal. That would clear things up.

Thank for your time.

**Comment by johnweldon** [comment]
Thanks!
