### ISSUE TITLE
filter by memberOf + nested groups

### ISSUE THREAD

**Issue by tmalkowski** [go-ldap/ldap#28]
Is the following search filter possible with this library? Didn't seem like it worked, based on my limited testing with a hacked up example_test.go.

```
memberOf:CN=Some-App-Group,OU=Groups,DC=example,DC=com
```

Also, is it possible to search nested group membership, similar to the following?

```
memberOf:1.2.840.113556.1.4.1941:=CN=Some-App-Group,OU=Groups,DC=example,DC=com
```

Apologies if this is obvious in the code -- I'm not a Go developer but need to add this functionality to an app that uses this library.

**Comment by stevekuznetsov** [comment]
I'm not positive on this, but from my testing, `memberOf` is often implemented using an attribute on the user entry or a pseudo-attribute created at runtime. In either case, this package is able to retrieve this type of data. I've done tests with OpenLDAP to verify this.

**Comment by tmmukunn** [comment]
would need support for using the ExtensionMatch filter.  When trying to use memberOf:1.2.840.113556.1.4.194, it tells the ldap server its doing an EqualityMatch instead of the ExtensionMatch from what I can tell in Wireshark.

**Comment by stevekuznetsov** [comment]
Very interesting. Could you please give me more information on your setup? What LDAP server/client are you running? Do you have a MWE `ldif`?

**Comment by tmmukunn** [comment]
The server is Microsoft Active Directory.  The client is grafana, the same client as specified by tmalkowski.  I'm not quite sure what MWE ldif is.

**Comment by stevekuznetsov** [comment]
Sorry, I meant an `ldif` file that is a minimum working example to seed the server with so that the request being sent reproduces the problem.

@liggitt I think we will need to set up an AD server to test this ASAP.

**Comment by liggitt** [comment]
I'll look at adding extension match filter parsing

**Comment by tmmukunn** [comment]
I'll see what I can do with creating a ldif.  
Here's an example of what i'm trying to get with ldapsearch: Substitute [ldapPassword] and [ldapuserDN] with the password, and DistinguishedName of the ldap user
ldapsearch -x -w '[ldapPassword] -D "[ldapUserDN]" "(member:1.2.840.113556.1.4.1941:=CN=User1,OU=blah,DC=rochester,DC=net)" 
That will return me not only the direct members of User1, but also the indirect members.  Suppose Role_Alpha is a member of TASK_Grafana_Admins and TASK_Generator_Operators and User1 is a member of Role_Alpha.  The ldap search should return all three 3 groups: Role_Alpha, TASK_Grafana_Admins and TASK_Generator_Operators.

**Comment by liggitt** [comment]
@tmalkowski can you check out the branch for https://github.com/go-ldap/ldap/pull/43 and see if that fixes the `(member:1.2.840.113556.1.4.1941:=CN=User1,OU=blah,DC=rochester,DC=net)` query for you?

**Comment by liggitt** [comment]
@tmmukunn if you want to try as well, that would be helpful

**Comment by tmalkowski** [comment]
@liggit I can confirm this is now working as expected, I've included the query I'm using in my hacked up example_test.go in case it helps anyone else.

```
	searchRequest := ldap.NewSearchRequest(
		baseDN,
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		"(&(objectClass=person)(memberof:1.2.840.113556.1.4.1941:=CN=APP-TR-Grafana-Admins,OU=App Groups,OU=Groups,OU=Objects,DC=example,DC=edu))",
		[]string{"dn", "cn"},                    // A list attributes to retrieve
		nil,
	)
```

**Comment by tmmukunn** [comment]
I am able to verify it as well, using both member and memberOf.  Thanks!

**Comment by liggitt** [comment]
Tagged in https://github.com/go-ldap/ldap/releases/tag/v2.2
