### ISSUE TITLE
How to set the user to a state where he cannot change his password?

### ISSUE THREAD

**Issue by Kotodian** [go-ldap/ldap#282]

**Comment by Kotodian** [comment]
How to set password policy: pwdAllowUserChange

**Comment by Kotodian** [comment]
![image](https://user-images.githubusercontent.com/22030659/89629257-16784780-d8d0-11ea-9220-42679a6c8c13.png)
I want to use it.But I really don't know what's that mean

**Comment by Kotodian** [comment]
https://docs.microsoft.com/zh-cn/windows/win32/adsi/modifying-user-cannot-change-password-ldap-provider?redirectedfrom=MSDN Do you know how this works?

**Comment by stefanmcshane** [comment]
Closing this out as the solution relates to specific implementations of ACLs which changes between LDAP implementations. 
Usually these types of changes tend to be applied by group policy.

If you solve your issue using go-ldap, please open a PR with the new extended functionality!
