### ISSUE TITLE
When I get this attribute.It returns a garbled answer.Do you how to deal with it? thx

### ISSUE THREAD

**Issue by Kotodian** [go-ldap/ldap#283]
![image](https://user-images.githubusercontent.com/22030659/89701812-0bbfc000-d96d-11ea-934e-2540da2b116c.png)

**Comment by stefanmcshane** [comment]
NTSecurityDescriptor is a Microsoft format
https://docs.microsoft.com/en-us/windows/win32/adschema/a-ntsecuritydescriptor

We currently don’t have any support for this, but are open to contributions!

They bit breakdown of ACLs are listed here:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/20233ed8-a6c6-4097-aafa-dd545ed24428

**Comment by Kotodian** [comment]
> NTSecurityDescriptor is a Microsoft format
> https://docs.microsoft.com/en-us/windows/win32/adschema/a-ntsecuritydescriptor
> 
> We currently don’t have any support for this, but are open to contributions!
> 
> The bit breakdown of ACLs are listed here:
> https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/20233ed8-a6c6-4097-aafa-dd545ed24428

thx but is this my console's problem or the data is wrong?

**Comment by Kotodian** [comment]
> > NTSecurityDescriptor is a Microsoft format
> > https://docs.microsoft.com/en-us/windows/win32/adschema/a-ntsecuritydescriptor
> > We currently don’t have any support for this, but are open to contributions!
> > The bit breakdown of ACLs are listed here:
> > https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/20233ed8-a6c6-4097-aafa-dd545ed24428
> 
> thx but is this my console's problem or the data is wrong?

I know the acl.But the output is grabled.I don't have any idea to deal with it.I just want to know what caused this case. Do you know Why?thanks

**Comment by stefanmcshane** [comment]
The console is doing its best to render an unknown file encoding. AD is returning NTSecurityDescriptor is a byte format, but doesn’t know how to decode it, so is attempting to treat the byteslice as UTF-16 most likely. 

You can see the actual binary using `binary.BigEndian.Uint16(yourByteSlice)`

Your data is correct, the library is returning the value as expected, and your console is interpreting as best it can without further direction. This specific format is a Microsoft-specific format, which we haven’t created an interpreter for yet.

**Comment by Kotodian** [comment]
> The console is doing its best to render an unknown file encoding. AD is returning NTSecurityDescriptor is a byte format, but doesn’t know how to decode it, so is attempting to treat the byteslice as UTF-16 most likely.
> 
> You can see the actual binary using `binary.BigEndian.Uint16(yourByteSlice)`
> 
> Your data is correct, the library is returning the value as expected, and your console is interpreting as best it can without further direction. This specific format is a Microsoft-specific format, which we haven’t created an interpreter for yet.

I used this function.It returned a value that type is uint16,Should I convert it to binary? thanks

**Comment by Kotodian** [comment]
![image](https://user-images.githubusercontent.com/22030659/89745121-31230a00-dae4-11ea-9fa3-564586f6df1c.png)
Can it turn to this string? thanks

**Comment by stefanmcshane** [comment]
Edited the comment there - my bad. 
This will print out the binary representation of the ACL, but will not be human readable unless you apply the aforementioned documentation from Microsoft

**Comment by Kotodian** [comment]
> Edited the comment there - my bad.
> This will print out the binary representation of the ACL, but will not be human readable unless you apply the aforementioned documentation from Microsoft

https://github.com/hectane/go-acl Can I use this tool to interpret it? I'm only a new programmer.I'm not good at programming.thx

**Comment by stefanmcshane** [comment]
I'm not sure about that module - I would contact the owner to see if that can parse the attributes you are looking for. Going to close this out in the meantime. Feel free to open a PR if you would like to contribute the solution that you come up with for parsing!

**Comment by Kotodian** [comment]
https://www.itinsights.org/Process-low-level-NtSecurityDescriptor/
this article helped me to parse it.But It is really sophisticated
