### ISSUE TITLE
module declares its path as: github.com/go-ldap/ldap/v3

### ISSUE THREAD

**Issue by xxwassyxx** [go-ldap/ldap#284]
When I try and get this module I get the following error.
```
go get gopkg.in/ldap.v3
go: gopkg.in/ldap.v3 upgrade => v3.1.3
go get: gopkg.in/ldap.v3@v3.1.3: parsing go.mod:
	module declares its path as: github.com/go-ldap/ldap/v3
	        but was required as: gopkg.in/ldap.v3
```
However if I add this to my go.mod file manually and change he version to 3.1.0 then there is no issue.

**Comment by stefanmcshane** [comment]
Hi @xxwassyxx, you are using the old import path which was deprecated with Go 1.11. Please update your import path to `github.com/go-ldap/ldap/v3` in your go.mod, or use `go get github.com/go-ldap/ldap/v3` to use the latest version. 

Further instructions are available on the Readme at this time. 

Thanks,
Stefan
