### ISSUE TITLE
Unable to verify certificate from AD AutoEnrollment

### ISSUE THREAD

**Issue by trdyer** [go-ldap/ldap#285]
Hey,

My AD Domain is using "AD AutoEnrollment" to generate certificates for all domain controllers. I am told that it is normal that the certificate's generated by auto-enrollment are for the host only, and not also for the domain. My problem is that because I am trying to connect to the domain, certificate validation is failing because dc01.bar.com !== bar.com. 

Is there a known/good/secure way around this problem?

**Comment by stefanmcshane** [comment]
Hi @trdyer,

Im AFK to right now to get you the actual commands, but you should be able to log into your DC and export the cert from the cert store. 
If you have many DCs, a wildcard cert should also work. 

Thanks,
Stefan

**Comment by trdyer** [comment]
Thanks @stefanmcshane, the issue isn’t exporting the cert. In my opinion it makes sense that it wouldn’t validate, my IT swears that it is correct to not have the individual domain controllers have a cert for the domain, that the cert should only be for the individual domain controller.

Does that make sense?

I think to make the tls.Dial() call I would need to connect with InsecureSkipVerify get the list of domain controllers and connect directly to a domain controller, but that seems _very_ wrong to me.

**Comment by stefanmcshane** [comment]
Hi @trdyer,

In theory, you are both correct. Inside the scope of this module, enabling InsecureSkipVerify can open some serious security issues by allowing untrusted access. 

Outside the scope of this module and without direct insight into your domain, it’s typical that sysadmins want to use a single cert per DC. Wildcards are often avoiding for this, as you cannot* revoke permissions for a single DC if it becomes compromised.

Based on what you have said, under the assumption that your PKI policy isn’t going to change, the best route would be to either: 
- have all your DCs upload their respective certs to a vault/store that can be programmatically accessed so you can pull the appropriate cert just in time. Hashicorp Vault is a commonly used OSS product for this (and I’m in no way affiliated. Ive just used it in this way previously)
- if you’re deploying your application on a low number of servers, have your certs added to the stores of those servers using GPOs, Puppet, or a endpoint management strategy similar to these. Equally, you could do this manually as part of your deployment steps. 

This isn’t an exhaustive list, and there are a lot more ways to manage certs at scale, but variations of these tend to be commonly used in SME.

**Comment by stefanmcshane** [comment]
Can't comment on your specific MS question, but can say that if you have a list of domain controllers, your issue should be resolved.

Let me know if we can close this out, as it sounds like an implementation decision as opposed to a module change.

Thanks,
Stefan
