### ISSUE TITLE
Drop support for legacy Go versions <1.7

### ISSUE THREAD

**Issue by stefanmcshane** [go-ldap/ldap#287]
Drop legacy support for Go versions <1.7 as builds are breaking due to introductions in the test package since 1.6
#286 as an example
https://golang.org/pkg/testing/#T.Run

Go 1.6 was last supported in 2017, when Go 1.8 was released.
https://golang.org/doc/devel/release.html#policy
https://blog.golang.org/go1.8

**Comment by johnweldon** [comment]
I'm surprised we missed this previously when the `t.Run` calls were added.

Nevertheless, I support updating the minimum supported version to 1.8
