### ISSUE TITLE
search with empty filter throws error

### ISSUE THREAD

**Issue by chiptus** [go-ldap/ldap#294]
when searching `ldapsearch -x -b "dc=mydomain,dc=com" -H ldap://192.168.1.104 -D "cn=admin,dc=mydomain,dc=com" -W` I would get the whole results under `cn=admin,dc=mydomain,dc=com` but since SearchRequest doesn't support nil filter, sending an empty filter returns `LDAP Result Code 201 "Filter Compile Error": ldap: filter does not start with an '('`.

**Comment by xNevo** [comment]
Hi,

ldapsearch automatically uses `(objectclass=*)` in case the user doesn't define one when executing the command. If you don't have an attribute to use I suggest you use the same filter as ldapsearch does.

See: https://github.com/openldap/openldap/blob/master/clients/tools/ldapsearch.c#L1044

**Comment by stefanmcshane** [comment]
Hi @chiptus,

Did you have any success with @xNevo's solution?

Thanks,
Stefan

**Comment by chiptus** [comment]
Hey Stefan,

we did send a default but a different than suggested.

Thanks,
Chaim

**Comment by stefanmcshane** [comment]
Fantastic. I’m glad to hear that you got it sorted out. Going to close this out, but if you would like to edit your comment to include your solution for future readers, we would appreciate it!

**Comment by chiptus** [comment]
I think actually yours is better than what we did. I would consider adding
a default to the library, but I also understand why not.

Thanks for being responsive.

>
