### ISSUE TITLE
How can user change its own password when binded to Active Directory?

### ISSUE THREAD

**Issue by martjarvi** [go-ldap/ldap#297]
Currently NewModifyRequest and NewPasswordModifyRequest cannot be used.

**Comment by stefanmcshane** [comment]
Hi @martjarvi,

Can you provide more context including the code you are using, the errors received, AD versions etc.?

We use these functions in production code internally which seem to work fine. 

Thanks,
Stefan

**Comment by martjarvi** [comment]
hi thanks for the reply @stefanmcshane.
We are using AD 2016.

I have very simple code:

conn := Login2Ldap(config.Get().LdapUrl, userDn, userPassword)
passwdModReq := ldap.NewPasswordModifyRequest(userDn, userPassword, newPassword)
if _, err := conn.PasswordModify(passwdModReq); err != nil {
	return err
}

Password could not be changed: LDAP Result Code 2 "Protocol Error": 0000203D: LdapErr: DSID-0C0911F4, comment: Unknown extended request OID, data 0, v3839

**Comment by stefanmcshane** [comment]
You need to ensure that your password is encoded - try something like the below and let me know how you get on

```newPassword := "test12345"
dn := "ou=user,dc=name"
password := fmt.Sprintf("\"%s\"", newPassword)

utf16 := unicode.UTF16(unicode.LittleEndian, unicode.IgnoreBOM)
pwdEncoded, err := utf16.NewEncoder().String(password)
if err != nil {
	e := fmt.Sprintf("Error encoding password: %s", err.Error())
	log.Fatal(e)
}

m := ldap.NewModifyRequest(dn, nil)
m.Replace("unicodePwd", []string{pwdEncoded})
err = myLDAPClient.Modify(m)
if err != nil {
	e := fmt.Sprintf("Error applying encoded password: %s", err.Error())
	log.Fatal(e)
}

**Comment by martjarvi** [comment]
I'm using this code to reset the users password with the administrative account, but in order to correctly set the new password (for example let the AD check the users password history etc), user need to bind with its own credentials.
When binding with the users credentials the ldap.modify request gives:

Password could not be changed: LDAP Result Code 50 "Insufficient Access Rights": 00000005: SecErr: DSID-031A11D7, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0

This is probably because the modify request demands administrative privileges.

**Comment by stefanmcshane** [comment]
Hi @martjarvi,
The response you are receiving seems to be coming from your ldap server, which would suggest that this is an issue on the server side with permissions. 
If you believe that this is an issue with the ldap module, please submit a PR with the proposed fix, or provide further details on your ldap server setup which is prohibiting the password reset. 

Thanks,
Stefan

**Comment by martjarvi** [comment]
It seems I got it working using this: https://gist.github.com/Project0/61c13130563cf7f595e031d54fe55aab

**Comment by stefanmcshane** [comment]
Great to hear that they were able to resolve with our package! Going to close this one out!

Thanks,
Stefan

**Comment by kong62** [comment]
> I'm using this code to reset the users password with the administrative account, but in order to correctly set the new password (for example let the AD check the users password history etc), user need to bind with its own credentials. When binding with the users credentials the ldap.modify request gives:
> 
> Password could not be changed: LDAP Result Code 50 "Insufficient Access Rights": 00000005: SecErr: DSID-031A11D7, problem 4003 (INSUFF_ACCESS_RIGHTS), data 0
> 
> This is probably because the modify request demands administrative privileges.

need add user to adminstrators group.

but not sercitry.

**Comment by DevOpserzhao** [comment]
> hi thanks for the reply @stefanmcshane. We are using AD 2016.
> 
> I have very simple code:
> 
> conn := Login2Ldap(config.Get().LdapUrl, userDn, userPassword) passwdModReq := ldap.NewPasswordModifyRequest(userDn, userPassword, newPassword) if _, err := conn.PasswordModify(passwdModReq); err != nil { return err }
> 
> Password could not be changed: LDAP Result Code 2 "Protocol Error": 0000203D: LdapErr: DSID-0C0911F4, comment: Unknown extended request OID, data 0, v3839

It happened to me, too.
