### ISSUE TITLE
LDAP Result Code 200 "Network Error"

### ISSUE THREAD

**Issue by dai3023273** [go-ldap/ldap#298]
l, err := ldap.Dial("tcp","ldap.example.com:389")
if err != nil {
	log.Fatal(err)
}
defer l.Close()
err = l.StartTLS(&tls.Config{
	InsecureSkipVerify: true,
})
if err != nil {
	fmt.Printf("TLS err:%s \n", err.Error())
	log.Fatal(err)
}

**Comment by stefanmcshane** [comment]
Hi @dai3023273,

Depending on your setup milage may vary, but can you please try connect on the LDAPS port (636)?
We would need more context to diagnose further. 

Thanks,
Stefan

**Comment by dai3023273** [comment]
l, err := ldap.DialTLS("tcp", "127.0.0.1:636", &tls.Config{InsecureSkipVerify: true})
	if err != nil {
		fmt.Printf("err:%s", err.Error()) //err:LDAP Result Code 200 "Network Error": EOF% 
		return
	}
error:err:LDAP Result Code 200 "Network Error": EOF%

**Comment by stefanmcshane** [comment]
Hi @dai3023273,

I suspect that this is an issue with your certificate setup. Please confirm that your LDAP server will allow insecure TLS connections. If you have confirmed that, another approach could be to try the example [here](https://github.com/go-ldap/ldap/blob/c9551dc8a15abc270d5ea1a59366622cba6c09a5/examples_test.go#L53).
As mentioned above, this seems more like an issue in the setup/understanding on the setup as opposed to a client library issue.

If you can provide more context, please open a new ticket as I'm closing this one out for now.

**Comment by scottmmjackson** [comment]
@stefanmcshane `EOF` as a result typically doesn't imply that certificate exchange has happened. I believe the point at which you will get this error is when the server rejects the TLS HELLO, which is before the certificate exchange process.

Additionally, the server has no way of understanding a client's `InsecureSkipVerify`, it's a client instruction that tells the client to ignore discrepancies with the server certificate. The connection is still encrypted over TLS, but you lose the security guarantees of certificate validity.

I'd be interested to see @daijiezou's information on server vendor, as we've been encountering `EOF` on Oracle Enterprise Directory Server over LDAPS- even if it's just to better understand limitations here.
