### ISSUE TITLE
Multi Factor Authenticate (MFA)

### ISSUE THREAD

**Issue by rahman74** [go-ldap/ldap#308]
Hello, 
Can this library login using MFA?

**Comment by stefanmcshane** [comment]
Hi @rahman74,

There is nothing in this library that would prevent you from using MFA login steps, however the strategy would depend entirely on what your setup looks like, and how you have implemented your 2FA. 
LDAP protocol itself doesn’t implement MFA, and is usually done through another service over SAML or similar. 

 Thanks,
Stefan

**Comment by stefanmcshane** [comment]
Closing as this should be implemented external to the go-ldap library
