### ISSUE TITLE
DialURL with timeout example

### ISSUE THREAD

**Issue by esgn** [go-ldap/ldap#310]
Hi all,

I'm trying to use `DialURL()` with a custom timeout. It could be nice if `example_test.go` would include such an example. Since v3, I understand it's all about passing the correct `DialOpt` to `DialURL()` but being relatively new to Go I'm still trying to find the proper way to achieve it.

Thanks in advance

**Comment by esgn** [comment]
Answering my own question ;) 

Found a clue in `lpad_test.go` where `DialWithTLSConfig(&tls.Config{InsecureSkipVerify: true})` is passed as opt in `DialURL()`.

I've tested the following expression and it seems to work : 
```
l, err := ldap.DialURL(ldapURL, ldap.DialWithDialer(&net.Dialer{Timeout: 3 * time.Second}))
```

**Comment by stefanmcshane** [comment]
Apologies for the slow reply @esgn, but you managed to solve this yourself.

Per [DialURL](https://github.com/go-ldap/ldap/blob/c9551dc8a15abc270d5ea1a59366622cba6c09a5/v3/conn.go#L199)

If you would like to contribute to the library, please open a PR with an example in `examples_test.go` and we will get it merged. If not, feel free to close the issue as complete!

Thanks,
Stefan
