### ISSUE TITLE
Making requests to the AD on behalf of the user who started the application.

### ISSUE THREAD

**Issue by vps2** [go-ldap/ldap#312]
Hi all! I want to write an application that will search in Active Directory. Can I make requests on behalf of the AD user who started the app? I would not like to save the username and password required for the bind function anywhere. The application will run from under Windows.

**Comment by stefanmcshane** [comment]
Hi @vps2, by default, we do not store the user that you bind with in the library. Depending on the architecture of your application, there would be many ways to solve this.
In short, you could store the `Conn` that you did the original bind with. If you have anonymous binds enabled, that could be another option.
