### ISSUE TITLE
[feature request] implement "whoami" (RFC4532)

### ISSUE THREAD

**Issue by johnnybubonic** [go-ldap/ldap#313]
Per [RFC4532](https://tools.ietf.org/html/rfc4532), this can be done via an extended request with OID `1.3.6.1.4.1.4203.1.11.3`.

It seems this is already implemented in the (presumably no-longer-maintained) [samuel/go-ldap](https://github.com/samuel/go-ldap) library ([here](https://github.com/samuel/go-ldap/blob/09b1a56d27556db648269ff780db35705dd55ca4/ldap/client.go#L315-L335)).

**Comment by stefanmcshane** [comment]
Hi @johnnybubonic,

Feel free to contribute a PR to implement this feature. Let me know if you need any help figuring out where it needs to go etc.

Thanks,
Stefan

**Comment by stefanmcshane** [comment]
Hi @johnnybubonic,
This has been implemented in #318 and will be merged soon. Let me know if it fits your usecases, or you have any issues.

Thanks,
Stefan
