### ISSUE TITLE
Support LDAP Unbind

### ISSUE THREAD

**Issue by arusso** [go-ldap/ldap#324]
We'd like to be able to issue an Unbind() before a Close() that closes the TCP connections so that the LDAP server can cleanly shutdown the LDAP connection.

Otherwise our LDAP server shows a B1 error when the connection is tore down which obfuscates whether a real issue is occurring or not, since the [B1 connection code](https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html/configuration_command_and_file_reference/logs-reference) is shared with errors related to corrupt BER elements.

I see this was rejected in #79, but I think it's worth re-evaluating since the use case here is a bit different.

**Comment by xNevo** [comment]
@arusso I submitted a PR to add an `Unbind` function. Let's see if this will get merged :)
