### ISSUE TITLE
unable to build app

### ISSUE THREAD

**Issue by prabhinmp** [go-ldap/ldap#331]
Hi ,
getting below error while building the app

This is the app which I'm trying to build

https://github.com/weibeld/k8s-ldap-authentication

```
main.go:6:2: no required module provides package github.com/go-ldap/ldap: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:8:2: no required module provides package k8s.io/api/authentication/v1: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

**Comment by johnweldon** [comment]
The referenced app is not configured to use Go modules; you probably need to run: `go mod init <module name>; go mod verify` and maybe `go mod tidy`; then you should be able to run `go build ` to successfully compile that app.
