### ISSUE TITLE
Connection being removed(?) if connecting in another func

### ISSUE THREAD

**Issue by johnnybubonic** [go-ldap/ldap#332]
I'm not sure how to explain this, so refer to the examples below.

Note the output and behavior of these two examples.

**A:**
```go
package main

import (
	"crypto/tls"
	"fmt"

	"github.com/go-ldap/ldap/v3"
)

func connect(c *ldap.Conn) (err error) {

	var tlsConf *tls.Config

	fmt.Printf("FUNC: *ldap.Conn before connect:\n%#v\n\n", c)

	server := "foo.domain.tld"
	bindDn := "cn=username,ou=people,dc=domain,dc=tld"
	passwd := "password"

	tlsConf = new(tls.Config)
	tlsConf.ServerName = server

	if c, err = ldap.DialURL(fmt.Sprintf("ldap://%v:389", server)); err != nil {
		return
	}

	if err = c.StartTLS(tlsConf); err != nil {
		return
	}

	if err = c.Bind(bindDn, passwd); err != nil {
		return
	}

	fmt.Printf("FUNC: *ldap.Conn after connect:\n%#v\n\n", c)


	return
}

func search(c *ldap.Conn) (result *ldap.SearchResult, err error) {

	var search *ldap.SearchRequest

	fmt.Printf("FUNC: *ldap.Conn before search:\n%#v\n\n", c)
	search = ldap.NewSearchRequest(
		"ou=things,dc=domain,dc=tld",
		ldap.ScopeWholeSubtree,
		ldap.DerefAlways,
		0,
		10,
		false,
		"(&(cn=objectname)(objectClass=groupOfNames))",
		[]string{"cn"},
		nil,
	)

	if result, err = c.Search(search); err != nil {
		return
	}
	fmt.Printf("FUNC: *ldap.Conn after search:\n%#v\n\n", c)

	return
}

func main() {

	var err error
	var l *ldap.Conn
	var result *ldap.SearchResult

	fmt.Printf("MAIN: *ldap.Conn before connect:\n%#v\n\n", l)

	l = new(ldap.Conn)
	if err = connect(l); err != nil {
		fmt.Println(err)
		return
	}
	fmt.Printf("MAIN: *ldap.Conn after connect, before search:\n%#v\n\n", l)

	if result, err = search(l); err != nil {
		fmt.Println(err)
		return
	}

	for _, e := range result.Entries {
		fmt.Printf("%v CN: %v\n", e.DN, e.GetAttributeValue("cn"))
	}
	fmt.Printf("MAIN: *ldap.Conn after search:\n%#v\n\n", l)

	l.Close()

}
```

**B:**
```go
package main

import (
	"crypto/tls"
	"fmt"

	"github.com/go-ldap/ldap/v3"
)

func main() {

	var err error
	var l *ldap.Conn
	var result *ldap.SearchResult
	var search *ldap.SearchRequest
	var tlsConf *tls.Config

	server := "foo.domain.tld"
	bindDn := "cn=username,ou=people,dc=domain,dc=tld"
	passwd := "password"

	fmt.Printf("MAIN: *ldap.Conn before connect:\n%#v\n\n", l)

	l = new(ldap.Conn)
	tlsConf = new(tls.Config)
	tlsConf.ServerName = server

	if l, err = ldap.DialURL(fmt.Sprintf("ldap://%v:389", server)); err != nil {
		fmt.Println(err)
		return
	}

	if err = l.StartTLS(tlsConf); err != nil {
		fmt.Println(err)
		return
	}

	if err = l.Bind(bindDn, passwd); err != nil {
		fmt.Println(err)
		return
	}

	fmt.Printf("MAIN: *ldap.Conn after connect, before search:\n%#v\n\n", l)


	search = ldap.NewSearchRequest(
		"ou=things,dc=domain,dc=tld",
		ldap.ScopeWholeSubtree,
		ldap.DerefAlways,
		0,
		10,
		false,
		"(&(cn=objectname)(objectClass=groupOfNames))",
		[]string{"cn"},
		nil,
	)

	if result, err = l.Search(search); err != nil {
		fmt.Println(err)
		return
	}

	for _, e := range result.Entries {
		fmt.Printf("%v CN: %v\n", e.DN, e.GetAttributeValue("cn"))
	}
	fmt.Printf("MAIN: *ldap.Conn after search:\n%#v\n\n", l)

	l.Close()

}
```

**A** will always hang -- forever, as far as I can tell -- as soon as the search is performed. Presumably this is a result of -- and this is probably a much bigger issue -- `c.conn`/`l.conn` transforming from a populated `*tls.Conn` to a *nil `net.Conn`* (and some various other attributes changing to nil) as SOON as the `connect()` func is returned. **There was no `defer l.Close()`.** There is a single Close() called, and that's at the end of `main()`. I have to manually kill it.

I have confirmed via TLSConnectionState() that yes, the TLS state is valid and populated after the StartTLS() but before leaving the `connect()` func, and false and all nil'd/zero'd out after leaving `connect()`. Which frankly makes no sense.

**B** always works just fine. The exact same code. The only difference is one is split apart into different functions, but this should not matter as `l`/`c` is a *ldap.Conn. Are you doing some really weird things with scoping logic?

This is on v3.3.0 using Go 1.16, but I can reproduce at the very least on v3.2.4 as well. I didn't test any other versions but I presume it holds the same.

**Comment by johnnybubonic** [comment]
Also worth nothing I can reproduce this with two different servers.

**Comment by xNevo** [comment]
After debugging a bit, @johnnybubonic it seems the problem comes from `nextMessageID()`, as `c` is not initialized and nil. Therefore, the channel will hang until forever.

The funny thing is, as you described: You pass a pointer to `connect`. After leaving the function the pointer should still point to the established ldap.Conn coming from `connect`, but it doesn't..

I'll dig around a bit more. This is very strange...

**Comment by xNevo** [comment]
Ok, [as function arguments are passed as value](https://stackoverflow.com/questions/52969722/function-is-not-changing-the-pointer-after-return), the pointer to the `ldap.Conn` is of course disregarded, as we're working with a copy in `connect`..

You can get around this by either:

1. Use Go-stylish function signatures: Return the `ldap.Conn` and error in connect instead of passing a pointer to it
```go
func connect() (conn *ldap.Conn, err error) {
	server := ""
	bindDn := ""
	passwd := ""

	if conn, err = ldap.DialURL(fmt.Sprintf("ldap://%v:389", server)); err != nil {
		return
	}

	err = conn.Bind(bindDn, passwd)
	return
}

func main() {
	var err error
	var result *ldap.SearchResult

	l, err := connect()
	if err != nil {
		fmt.Println(err)
		return
	}

	if result, err = search(l); err != nil {
		fmt.Println(err)
		return
	}

	for _, e := range result.Entries {
		fmt.Printf("%v CN: %v\n", e.DN, e.GetAttributeValue("cn"))
	}
}
```


2. Dereference the new connection and point to `l` which has been defined outside:

```go
func connect(connection *ldap.Conn) (err error) {
	// ... 
	var newConn *ldap.Conn
	if newConn, err = ldap.DialURL(fmt.Sprintf("ldap://%v:389", server)); err != nil {
		return
	}

	if err = newConn.Bind(bindDn, passwd); err != nil {
		return
	}

	*connection = *newConn // <--
	return
}
```

**Comment by xNevo** [comment]
Imo this is not a bug of the library, since it's part of the Go specs to copy-by-value + You initialized the variable `var l *ldap.Conn` yourself in a unconventional way.. As mentioned, it would be more Go-stylish if you resorted to another function signature, but we can give it a try. I'll make PR and implement a check for initialization before doing any requests.

**Comment by johnnybubonic** [comment]
Yeah... you're right in that. I was a bit distracted when I replied and didn't fully mentally parse the actual cause.

Ideally, ldap.Dial* **should**, in my opinion, have a func signature that matches [net.Dial](https://pkg.go.dev/net#Dial)'s where a value is returned instead. But that'd be a breaking change. In my actual code, the ldap.Conn is a struct field and ldap is conditionally connected based on an external caller's state, so it's a bit more complicated for me to do it "the right way", unfortunately.

But regardless of that, your PR is IMO a necessary improvement - an action that operates on a connection should *always* require that connection be previously initialized. That should at least remove the mysterious hang pitfall and would have made my dumbassery more apparent. Thank you for your input and work on this!
