### ISSUE TITLE
get ldap/v3 error

### ISSUE THREAD

**Issue by cw4t** [go-ldap/ldap#343]
when I try: **go get github.com/go-ldap/ldap/v3**

I got this:
```
go: downloading github.com/go-ldap/ldap/v3 v3.0.0
go: downloading github.com/go-ldap/ldap v2.5.1
go get github.com/go-ldap/ldap/v3: missing github.com/go-ldap/ldap/go.mod and .../v3/go.mod at revision v3.0.0
```

Please help me

**Comment by cw4t** [comment]
go1.16.4

**Comment by johnweldon** [comment]
I'm unable to reproduce this - I suspect it's environmental.

Can you provide the output of `go env`?

Does running `go clean -cache` before `go get -v github.com/go-ldap/ldap/v3` help?

**Comment by cw4t** [comment]
I tried again and it worked,😂---- Replied Message ----FromJohn ***@***.***>Date10/30/2021 08:28 ***@***.***> ***@***.******@***.***>SubjectRe: [go-ldap/ldap] get ldap/v3 error (Issue #343)
I'm unable to reproduce this - I suspect it's environmental.
Can you provide the output of go env?
Does running go clean -cache before go get -v github.com/go-ldap/ldap/v3 help?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/go-ldap/ldap/issues/343#issuecomment-955112877",
"url": "https://github.com/go-ldap/ldap/issues/343#issuecomment-955112877",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
