### ISSUE TITLE
Semi colon is not treated as RDN separator

### ISSUE THREAD

**Issue by shaiacs** [go-ldap/ldap#351]
A DN may contain RDNs that are separated by semi colons. Looks like the current code doesn't handle this correctly.
I believe this can be fixed by changing the following lines in Dn.parseDn method:
Line 104 from:
`case char == ',' || char == '+':`
to:
`case char == ',' || char == '+' || char == ';':`

Line 112 from:
`if char == ',' {`
to:
`if char == ',' || char == ';' {`

**Comment by xNevo** [comment]
From [rfc2253](https://www.ietf.org/rfc/rfc2253.txt):

> 4.  Relationship with RFC 1779 and LDAPv2
>   [...] 
>   Implementations MUST allow a semicolon character to be used instead
>   of a comma to separate RDNs in a distinguished name, and MUST also
>   allow whitespace characters to be present on either side of the comma
>   or semicolon.  The whitespace characters are ignored, and the
>   semicolon replaced with a comma.

I'll look into this this week and propose a PR
