### ISSUE TITLE
External bind with LDAPS

### ISSUE THREAD

**Issue by zmb3** [go-ldap/ldap#354]
The example in #277 was super helpful and does work for me if I connect to `ldap://` on insecure port 389 and then upgrade with `StartTLS(cfg)`, but I'm getting `LDAP Result Code 7: Auth Method Not Supported` if I try to connect to `ldaps://` on port 636.

Works:
```
tc := &tls.Config{...}
conn, err := ldap.DialURL("ldap://ldap.example.com:389")
err = conn.StartTLS(tc)
err = conn.ExternalBind()
```

Doesn't work:
```
tc := &tls.Config{...}
conn, err := ldap.DialURL("ldaps://ldap.example.com:636", ldap.DialWithTLSConfig(tc))
err = conn.ExternalBind()
```

Should this work when dialing `ldaps://`?

**Comment by xNevo** [comment]
This really depends on the directory system and your configuration. As for the external authentication, there's no implementation specific problem as far as I can tell:

>    The EXTERNAL mechanism allows a client to request the server to use
   credentials established by means external to the mechanism to
   authenticate the client.  The external means may be, for instance, IP
   Security [RFC4301] or TLS [RFC4346] services.  In absence of some a
   priori agreement between the client and the server, the client cannot
   make any assumption as to what external means the server has used to
   obtain the client's credentials, nor make an assumption as to the
   form of credentials.  For example, the client cannot assume that the
   server will use the credentials the client has established via TLS.

May you share more informations with you, @zmb3 ?

**Comment by zmb3** [comment]
I'm running against Active Directory (Windows Server 2016).

I'm wondering if `StartTLS` does something different than the `DialWithTLSConfig` option.

**Comment by xNevo** [comment]
According to https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/8e73932f-70cf-46d6-88b1-8d9f86235e81#5112-using-ssltls:

> If the client establishes the SSL/TLS-protected connection by means of an LDAP_SERVER_START_TLS_OID operation, the authentication state of the connection remains the same after the operation as it was before the operation. The DC authenticates the connection as the credentials represented by the client's certificate only if an EXTERNAL SASL bind is subsequently performed. 

Are you sure you have the certificate properly set up in your var `tc`? Can you confirm that you can connect and authenticate to the server with the exact same credentials/certificates using `ldapsearch`?

**Comment by zmb3** [comment]
I'm using the same tls Config that I use to authenticate with StartTLS and that works fine, so I think that would suggest that things are configured properly.  

I will give ldapsearch a try and see what happens.

**Comment by zmb3** [comment]
Ah, thanks for the link you shared - the answer was in there!

> If the client establishes the SSL/TLS-protected connection by means of connecting on a protected LDAPS port, then the connection is considered to be immediately authenticated (bound) as the credentials represented by the client certificate. An EXTERNAL bind is not allowed, and the bind will be rejected with an error.

So there's no need for an external bind at all when connecting to the LDAPS port, the connection is authenticated and ready to use after the `DialURL` call completes. I confirmed this does work as expected!
