### ISSUE TITLE
How to do a nested query to get all users which are members of one of the child groups which are members of a parent group?

### ISSUE THREAD

**Issue by Pe-te** [go-ldap/ldap#355]
Hi, we need to make a query that gets all users that are member of a group that is a subgroup of another group.

The security groups are defined like this:

```
ChildGroup1.memberOf = ParentGroup
ChildGroup2.memberOf = ParentGroup
ChildGroup3.memberOf = ParentGroup
User1.memberOf = [ChildGroup1]
User2.memberOf = [ChildGroup1]
User3.memberOf = [ChildGroup2]
User4.memberOf = [ChildGroup3]
```
There will be new ChildGroups added in the future, so we cannot use them directly and have to use the ParentGroup.

With Powershell we can do the following query and get everything we need:

```
Get-ADGroupMember -Identity "CN=ParentGroup,OU=Company-Groups,DC=company,DC=com" -Recursive |
Get-AdUser -Properties UserPrincipalName,GivenName,Surname,Enabled,MemberOf

```
Additionally we need some extra attributes from the users, that's why we pipe the results it to Get-AdUser.

Is it possible to do the same with NewSearchQuery() or do we need to do multiple calls here?

**Comment by xNevo** [comment]
You'll need to do multiple search queries, this cannot be done through search filters. Powershell does the same under the hood to recursively fetch the user attributes of the group members.

**Comment by Pe-te** [comment]
Interesting, I stumbled over this gist, seems to do exactly what I need:
[tboerger/4840/file-gistfile1-txt](https://gist.github.com/tboerger/4840e1b5464fc26fbb165b168be23345#file-gistfile1-txt)

With a little modification I get everything in one function call.
Although it is probably many recursive queries under the hood as you say.

```golang
// filter for group and subgroups
filterDN = "(&(objectClass=person)(memberOf:1.2.840.113556.1.4.1941:=CN=ParentGroup,OU=Company-Groups,DC=company,DC=com))"
// search users here
baseDN = "DC=company,DC=com"
// get extra fields that are not present in the default request
userProperties := []string{"userPrincipalName", "givenName", "sn", "enabled", "memberOf"}
searchReq := ldap.NewSearchRequest(baseDN, ldap.ScopeWholeSubtree, ldap.DerefAlways, 0, 0, false, filterDN, userProperties, []ldap.Control{})
```

About the 1.2.840.113556.1.4.1941
https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx
