### ISSUE TITLE
wsasend: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by dpajkovic** [go-ldap/ldap#364]
Hello,

Running LDAP as a long-running service, after some time I get my error logs filled with the following errors:

`tls: failed to send closeNotify alert (but connection was closed anyway): write tcp <local IP address>:63427-><ip address of ldap server>:3269: wsasend: An existing connection was forcibly closed by the remote host.`

The LDAP functions keep working without any issue, it's just a matter of logs filling up.

If it's an important piece of information, the LDAP server address is a network load balanced address, and there are also firewalls (that of course let the LDAP connections through but might be picky when it comes to connection kept alive for long time).

**Comment by xNevo** [comment]
I don't think this is a library specific problem. I've been running a LDAP proxy using this lib which keeps a pool of open connections for as long as possible open for faster queries. I only got connection error messages when the directory server closed it on their end or if I lost my internet connection.

**Comment by dpajkovic** [comment]
Is there at least a way to stop this from filling up error logs? It is not going through the logging I have set up, and the error is not getting reported up the stack to any error I check for.

**Comment by xNevo** [comment]
This depends on how you implemented error logging. The simpliest version would be to check the error message:
```go
import (
	"fmt"
	"strings"
)

func main() {
	err := fmt.Errorf("tls: failed to send closeNotify alert (but connection was closed anyway): write tcp <local IP address>:63427-><ip address of ldap server>:3269: wsasend: An existing connection was forcibly closed by the remote host.")
	fmt.Println(strings.HasSuffix(err.Error(), "An existing connection was forcibly closed by the remote host."))
}
```
