### ISSUE TITLE
Support user-defined logger instance

### ISSUE THREAD

**Issue by n3integration** [go-ldap/ldap#365]
First off, thank you for creating the `go-ldap` library and sharing it with the community. 

Using the optional debug logger was helpful while integrating the library. When transitioning from dev/test to a prod version of an application, the debug logger can be disabled, which is super convenient. If a project that imports the library uses a custom logger instance, the library has a fallback to the default `log.Logger` instance in certain scenarios, which log the messages to stderr and may not be ideal. It would be helpful to inject a `log.Logger` instance into the library to handle these cases in a way that is consistent with the rest of the application.

If this is functionality that you think that others in the community would benefit from, I can submit a PR.

**Comment by johnweldon** [comment]
Thank you - yes, that sounds like a good improvement. Please feel free to submit a PR
I've been remiss in keeping up with issues lately, but I'll make an effort to get it reviewed and accepted, or one of the other maintainers might too.
