### ISSUE TITLE
How should I rename cn

### ISSUE THREAD

**Issue by eryajf** [go-ldap/ldap#378]
How should I rename cn

The demand is：

`ou=aa,ou=group,dc=eryajf,dc=net`

Revised

`ou=bb,ou=group,dc=eryajf,dc=net`

I see that there is such a rename function in the phpldapadmin.

**Comment by cpuschma** [comment]
Please see this function on how to change the DN:
https://github.com/go-ldap/ldap/blob/7d3b8d48feec050af443cf1a4281cf965416f5ab/v3/moddn.go#L17-L29

**Comment by eryajf** [comment]
Thank you, this is OK

```
    modify := ldap.NewModifyDNRequest("cn=aa,ou=group,dc=eryajf,dc=net", "cn=bb", true, "")
    return public.InitCli().ModifyDN(modify)
```
