### ISSUE TITLE
TimeLimit in SearchRequest

### ISSUE THREAD

**Issue by mirza-ali-ctct** [go-ldap/ldap#384]
I am looking to set connection timeout in `SearchRequest` and wondering what is the unit value(seconds/ms/etc..) of `TimeLimit`?

**Comment by cpuschma** [comment]
See https://datatracker.ietf.org/doc/html/rfc4511#section-4.5.1.5:
> A time limit that restricts the maximum time (in seconds) allowed for a Search.  A value of zero in this field indicates that no client requested time limit restrictions are in effect for the Search. Servers may also enforce a maximum time limit for the Search.

**Comment by cpuschma** [comment]
As we recently touched this part of the codebase:
https://github.com/go-ldap/ldap/blob/cb504ae2f5200bfbbf1cfe20e569ec1fe5789952/conn.go#L283-L286

You can go "as small" as a nanosecond for a timeout if you want to.
