### ISSUE TITLE
filter failed with chinese language

### ISSUE THREAD

**Issue by ljyf5593** [go-ldap/ldap#39]
Filter: "(&(objectclass=inetorgperson)(cn=中文))"

this filter will failed

**Comment by liggitt** [comment]
Can you describe what is failing? The filter compiles as I would expect. Can you enable Debug on your connection and include any (non-confidential) output?

**Comment by liggitt** [comment]
If a search is failing, what server are you running against? Does a less-specific filter return things? For example `(objectclass=inetorgperson)`?

**Comment by ljyf5593** [comment]
server is OpenLdap, when I use filter:"(&(objectclass=inetorgperson)(cn=test))", can find one,but use filter:"(&(objectclass=inetorgperson)(cn=中文))" find nothing, I use PHP Ldap extention can find.

**Comment by liggitt** [comment]
Found the issue, should be fixed in https://github.com/go-ldap/ldap/pull/43 if you want to pull that branch and try it out

**Comment by liggitt** [comment]
Tagged in https://github.com/go-ldap/ldap/releases/tag/v2.2
