### ISSUE TITLE
Support proxy

### ISSUE THREAD

**Issue by seblaz** [go-ldap/ldap#398]
Currently the options to configure the dialer receive a `net.Dialer` and that makes it impossible to replace such dialer with a custom one that passes through a proxy. The solution would be to depend on an interface instead of a concrete type for greater flexibility (the interface could be https://pkg.go.dev/golang.org/x/net/proxy#Dialer or https://pkg.go.dev/golang.org/x/net/proxy#ContextDialer for example). Another option would be to receive a function that returns a connection, like go-redis does https://pkg.go.dev/github.com/go-redis/redis/v8#Options.

**Comment by cpuschma** [comment]
I understand the problem, but see another big one with it:

The most minimal Go version (1.14) we support does not have the `Dialer` interface you mentioned. It would be easy to implement the interface with it's only method `Dial`, and replace it in the `DialContext` struct and it's methods, but `tls.DialWithDialer` only accepts dialers that are of type `*net.Dialer`.

Adhoc I can't think of a solution for this that would at least break backwards compatibility. An alternative would be to establish the connection manually and to create the LDAP connection instance by hand using `NewConn`, e.g.:

```go
myDialer := &yourCustomDialer{}
conn, err := myDialer.Dial("tcp", "127.0.0.1:389")
if err != nil {
    //
}

ldapConn := ldap.NewConn(conn, true) // The last arguments signals the ldap library if the connection is a tls connection
ldapConn.Start() // initialize the necessary ingress and egress goroutines 
```

**Comment by seblaz** [comment]
Thanks! I will give a try to the workaround
