### ISSUE TITLE
Bind as currently logged user

### ISSUE THREAD

**Issue by abolinhas** [go-ldap/ldap#403]
Hi
Is possible to bind as currectly logged user without put the username / password? Like this option in ldp.exe
![Screenshot_64](https://user-images.githubusercontent.com/3245485/202932819-519bdc94-731e-4201-bdee-fe0e6d0773d7.png)

**Comment by FlipB** [comment]
There's no way to do this on master branch currently, but you could try #402.
Since it's not vetted I'd suggest making sure traffic is encrypted and the server is trusted (so StartTLS and validate server certificate) *before* you attempt to bind.

**Comment by cpuschma** [comment]
The mentioned PR has been merged, you can use the SSPI GSSAPI SASL to authenticate as the currently running user.
