### ISSUE TITLE
Active Directory verify password

### ISSUE THREAD

**Issue by alexadmin** [go-ldap/ldap#408]
I need to integrate this project with Kubernetes (bare metal) and Active Directory.

I had seen this article https://itnext.io/implementing-ldap-authentication-for-kubernetes-732178ec2155
it reference to this project, but it's about OpenLDAP:
`fmt.Sprintf("(&(objectClass=inetOrgPerson)(cn=%s)(userPassword=%s))", username, password), // Filter`

And it doen't work with Active Directory, because Active Directory it doesn't store password in plaintext.

I had seen example:
`	// Bind as the user to verify their password
	err = l.Bind(userdn, password)
	if err != nil {
		log.Fatal(err)
	}`

https://github.com/go-ldap/ldap/blob/master/examples_test.go

Am I right? Should I use that?

**Comment by cpuschma** [comment]
You're right, Active Directory doesn't store the credentials in an accessible attribute. You'll have to use a bind request to verify the credentials.

https://github.com/go-ldap/ldap/blob/0e43630234df9d68e2ccd1bc19f6a781f2ddf315/examples_test.go#L13-L24

**Comment by alexadmin** [comment]
thank you.
