### ISSUE TITLE
Is it correct that ldap.ParseDN() considers string `dc=` as valid dn?

### ISSUE THREAD

**Issue by iredmail** [go-ldap/ldap#409]
Is it correct that ldap.ParseDN() considers string `dc=` as valid dn?

Reproduce it:

```
package main

import (
	"fmt"

	"github.com/go-ldap/ldap/v3"
)

func main() {
	dn, err := ldap.ParseDN("dc=")
	fmt.Printf("err == nil: %v\n", err == nil)
	fmt.Printf("dn: %v\n", dn)
}
```

Save it in file `main.go` and run `go run main.go`, output:
```
err == nil: true
dn: 
```

**Comment by cpuschma** [comment]
A distinguishedName is a sequence of RDNs, which in turn are AttributeTypeAndValue and simply key value pairs. Hence, the value can be empty and does not violate RFC2253.

**Comment by iredmail** [comment]
Thanks @cpuschma :)
