### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by Depado** [go-ldap/ldap#41]
Hi,
I intend to use your lib for a personnal project. I would like to know if this lib is currently stable and production ready. 

Thanks a lot for the amazing work anyway ! :+1:

**Comment by johnweldon** [comment]
@Depado yes, this library is being used in production by a few different projects already. [v1 examples](https://godoc.org/gopkg.in/ldap.v1?importers), and [v0 examples](https://godoc.org/gopkg.in/ldap.v0?importers)

We need to standardise the versioning, but the project is stable and production ready.

**Comment by Depado** [comment]
Thanks a lot @johnweldon for the quick answer and the info :+1:
