### ISSUE TITLE
LDAP Result Code 4 "Size Limit Exceeded":

### ISSUE THREAD

**Issue by lovechuxin** [go-ldap/ldap#415]
After the query exceeds 1000 entries, the LDAP Result Code 4 "Size Limit Exceeded" will be displayed:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/53209737/216001376-06ae3bf0-218b-42da-b8cb-26a34083611c.png">

**Comment by lovechuxin** [comment]
SearchWithPaging Successfully solved！

**Comment by zhaohao0707** [comment]
为什么我使用了SearchWithPaging还是会触发限制
