### ISSUE TITLE
Handling time ?

### ISSUE THREAD

**Issue by Depado** [go-ldap/ldap#42]
Hello,

Sorry for opening yet another issue, but any idea on how I can handle timestamps ? 

Thanks in advance :smile:

**Comment by johnweldon** [comment]
Hi @Depado ; do you have an example or a specific use case you're trying to achieve?

Cheers,

**Comment by Depado** [comment]
The idea is to have a micro-service that updates LDAP entries. The micro-service receives data in the form of a struct (using [kite](https://github.com/koding/kite)). When the micro-service receives a request, it connects to the LDAP and updates the corresponding entry. Now I want to insert in the LDAP the date (and time) at which that request happened.

**Comment by johnweldon** [comment]
I see - you want to update the [canonical](https://tools.ietf.org/html/rfc4512#section-3.4.4) `modifyTimestamp` attribute on the entity.

According to the linked RFC above, that should be updated by the server when using the Modify operation.

For example https://github.com/go-ldap/ldap/blob/master/example_test.go#L155-L162

**Comment by Depado** [comment]
That could indeed work. But what if I want to add my own timestamps ? For example, this request will indeed update the canonical modifyTimestamp attribute on the entity, but what if I need to have a custom field that contains a date ? 

Thanks a lot anyway, you're helping me a lot :)

**Comment by johnweldon** [comment]
I think it's as simple as adding a custom attribute and storing the timestamp however you choose.  [RFC 3339](https://tools.ietf.org/html/rfc3339) and [unix timestamps](https://en.wikipedia.org/wiki/Unix_time) seem to be popular ways of encoding date/time. And Go time package supports both [formatting](https://golang.org/pkg/time/#Time.Format) time to [rfc3339](https://golang.org/pkg/time/#pkg-constants), and extracting the [unix timestamp](https://golang.org/pkg/time/#Time.Unix).

**Comment by Depado** [comment]
Oh I see, so you would store it as a string ? And then when reading from the LDAP, you would convert the string back to a Go time.Time ?

Well that indeed solves my problem haha

Thanks a lot @johnweldon !

**Comment by vetinari** [comment]
When reading an entry with a GeneralizedTime syntax, the following works, depending on your LDAP server you might want to tweak the LDAPTimeMilliLayout to contain more fractional "0"s:
```go
package main

import (
    "fmt"
    "time"
)

func main () {
    var LDAPTimeLayout = "20060102150405Z"
    var LDAPTimeMilliLayout = "20060102150405.000Z"
    var modifyTimestamp = "20160206155227Z"
    var modifyTimestamp2 = "20160206155227.023Z"

    t, err := time.Parse(LDAPTimeLayout, modifyTimestamp)
    if err != nil {
        panic(err.Error())
    }
    fmt.Printf("modifyTimestamp=%s\n", t)
    fmt.Printf("LDAP -> %s\n", t.Format(LDAPTimeLayout))
    t, err = time.Parse(LDAPTimeMilliLayout, modifyTimestamp2)
    if err != nil {
        panic(err.Error())
    }
    fmt.Printf("modifyTimestamp2=%s\n", t)
}
```
