### ISSUE TITLE
Question - How to limit the number of results

### ISSUE THREAD

**Issue by abolinhas** [go-ldap/ldap#431]
Hi
I have a big active directory with a lot of entries, what i prented to achive with go-ldap is to retrive only the first 50 results.
I already try the size limit option or paging but always return all results.
Anyone can help me to limit the number of results per search?
Best regards

**Comment by cpuschma** [comment]
Hi,

SizeLimit should do the trick usually. Are you querying using `SearchWithPaging` or a normal search request? Additionally, you can reduce the search scope to one organizational unit and enumerate over them one by one if necessary until you hit your limit

**Comment by VakarisZ** [comment]
For me sizeLimit does nothing: 
![image](https://github.com/go-ldap/ldap/assets/36815064/9a0463ed-3dd1-4400-95ee-280deb3c5a97)

**Comment by VakarisZ** [comment]
LdapSearch `-z` option does nothing also. I think this has something to do with the ldap  setup, not a bug in this package

**Comment by GuoFlight** [comment]
I have the same problem.

**Comment by cpuschma** [comment]
I can replicate this issue, but it is not an implementation issue of the library. I analyzed the traffic with Wireshark and the SizeLimit attribute is correctly set and sent to the server.

I've created a patch and a PR to optionally enforce a size limit.

**Comment by cpuschma** [comment]
See #482
