### ISSUE TITLE
Google LDAP?

### ISSUE THREAD

**Issue by mark-a-johnson** [go-ldap/ldap#454]
Has anyone connected to Google using this library?  We've created a client in Google and get a cert, key (and username & password).  How is the connection configured with the cert/key?  Thanks!

**Comment by bambusoideae** [comment]
I use DialURL to connect Google LDAP. You can try this.
```
ldap.DialURL(p.URL, ldap.DialWithTLSConfig(tlsConfig))
```

**Comment by t2y** [comment]
@mark-a-johnson Next time, you can ask a question on GitHub discussions.

* https://github.com/orgs/go-ldap/discussions/categories/q-a

**Comment by gedw99** [comment]
Cloud Identity is $7.2/mo per user.

https://cloud.google.com/identity/#pricing
