### ISSUE TITLE
Grafana no longer retrieving list of user groups correctly after upgrade of ldap server

### ISSUE THREAD

**Issue by mwtzzz** [go-ldap/ldap#470]
We upgraded our ldap server from `2.4.49+dfsg-2ubuntu1.9` to `2.5.16+dfsg-0ubuntu0.22.04.1` and after doing this Grafana (which uses this go-ldap library) is no longer retrieving the complete list of user groups, it retrieves one and only one group (seems to be the last one) for each user. With the previous ldap server it was getting the user's complete list of groups. 

We think this is a problem with the go-ldap library because everything else in our environment (eg. Jenkins) is able to get all the user groups properly. 

Has anyone observed similar behavior? Does anyone know of a fix?

**Comment by cpuschma** [comment]
No response. Feel free to re-open this issue if you have more informations to help you with.
