### ISSUE TITLE
Brackets in name break filter compilation

### ISSUE THREAD

**Issue by djetelina** [go-ldap/ldap#477]
Hey,
my names sometimes look like `John Doe (EXT)`. This seems to break compiling, even though brackets should be valid characters. I am not proficient with golang by any stretch, but it seems that `case '(':` in compileFilter might be the cause? 

I tracked it going from ldap terraform provider to its underlying [library](https://github.com/Ouest-France/goldap/blob/master/user.go#L26), to here. There's not much I can do in code, since I don't interact with the code.

**Comment by cpuschma** [comment]
Using unparsed input in ldap filters is dangerous, you need to escape all corresponding characters using [`ldap.EscapeFilter`](https://pkg.go.dev/github.com/go-ldap/ldap/v3#EscapeFilter)

**Comment by djetelina** [comment]
Thanks a lot for the reply! My smarter colleague figured as much and opened a PR in the [right place](https://github.com/Ouest-France/terraform-provider-ldap/pull/111). Which means I can close my issue here then :)
