### ISSUE TITLE
Support for children search scope constant declaration

### ISSUE THREAD

**Issue by sirzzang** [go-ldap/ldap#481]
Hi. I want to search entries from LDAP server by using ‘children’ value in the scope option, similar to what is possible with the `-s` option in the [ldapsearch](https://www.openldap.org/software//man.cgi?query=ldapsearch&apropos=0&sektion=1&manpath=OpenLDAP+2.4-Release&format=html) command.

After trying out different approaches, I've come to realize that `SearchRequest` with scope argument set to value `3` does exactly what I wanted to do, but there is no constant declaration for representing this scope level. 
I know scope level for children is not defined in [RFC4511](https://datatracker.ietf.org/doc/html/rfc4511). However, I think adding constant declaration for children level would enhance convenience for users like me. Since the code using `SearchRequest` currently functions well with the scope argument value `3`, incorporating it into a constant declaration would add more clarity and coherence. 

Could you please review PR https://github.com/go-ldap/ldap/pull/480 and add support for it? 

Thanks.

**Comment by cpuschma** [comment]
Hi, #480  has been merged. Thank you for bringing this up and your contribution.

**Comment by sirzzang** [comment]
> Hi, #480 has been merged. Thank you for bringing this up and your contribution.

Thanks for quick response :) Thank you!
