### ISSUE TITLE
Not possible to connect ldap

### ISSUE THREAD

**Issue by raizdev** [go-ldap/ldap#512]
I am trying to migrate my nodejs application to go lang. 

I am able to connect in nodejs with the ldap-authentication library to the ldap server. But in go im getting the error: LDAP Result Code 200 "Network Error": dial tcp 10.8.24.10:636: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

I tried serveral things but couldnt figure out why this error occurs

any suggestions?

**Comment by cpuschma** [comment]
Can you show us the relevant code if possible? Thank you.

**Comment by raizdev** [comment]
Ofcourse! 

This is the code in ldap where I am able to log into ldap
```
    const { authenticate } = require('ldap-authentication');

    let options = {
        ldapOpts: {
            url: 'ldaps://ldaps.wnl.local:636,
            tlsOptions: { rejectUnauthorized: false },
        },
        userDn: req.body.username + '@wnl.local',
        username: req.body.username,
        userPassword: req.body.password,
        userSearchBase: 'OU=Managed Users,OU=KK,DC=wnl,DC=local',
        usernameAttribute: 'name',
        attributes: ['thumbnailPhoto;binary', 'givenName', 'sn', 'cn', 'dn', 'title', 'mail', 'memberOf', 'msExchExtensionAttribute34' , 'msExchExtensionAttribute16']
    };
```

In golang im trying to authenticate with

```
    ldapURL := "ldaps://ldaps.wnl.local:636"
    l, err := ldap.DialURL(ldapURL, ldap.DialWithTLSConfig(&tls.Config{InsecureSkipVerify: true}))
    if err != nil {
            log.Fatal(err)
    }
    defer l.Close()
```

**Comment by cpuschma** [comment]
The code looks OK to me. Looking at your error, the error looks to be coming from the Go `net` Dialer. The error message "connectex: An attempt was made to access a socket in a way forbidden by its access permissions" typically indicates a problem with the network access permissions or configuration on the system where your Go application is running. Do you have a XDR solution, an Antivirus or some sort of firewall enforcement running that could block your application from accessing the destination server?

**Comment by raizdev** [comment]
You're right! Windows is blocking my ass off at the moment. Even when I compile the program it gives the same error. Now I have it working via WSL. thanks for your thoughts!

**Comment by t2y** [comment]
@raizdev Use GitHub Discussions next time you have a question like this.

* https://github.com/orgs/go-ldap/discussions/categories/q-a

**Comment by raizdev** [comment]
> @raizdev Use GitHub Discussions next time you have a question like this.
> 
> * https://github.com/orgs/go-ldap/discussions/categories/q-a

Im sorry,  thanks for the headsup
