### ISSUE TITLE
[req] Implement ExtendedRequest request as a prereq to enable fast bind for AD

### ISSUE THREAD

**Issue by filimonic** [go-ldap/ldap#514]
Implement `ExtendedRequest` : rfc2251#section-4.12

Which adds ability to call something like `ldap.Conn#ExtendedRequest(LDAP_SERVER_FAST_BIND_OID, nil)`
Which switches LDAP connection to [`LDAP_OPT_FAST_CONCURRENT_BIND`](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/session-options) mode
Which reduces AD DS server load because 
> Unlike a normal LDAP bind, a concurrent bind does not determine a user group association or build a security token; it only determines if the user has a valid ID and password. This enables the concurrent bind to complete in a fraction of the time of a normal bind.

Ref: https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ldap/using-ldap-for-password-authentication
Ref: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/962a5f25-f541-48a6-b73c-da01f1b7fc69

**Comment by cpuschma** [comment]
@filimonic Thank you for your request. We implemented this in #516 recently. Feel free to checkout the master branch to try it out.
