### ISSUE TITLE
Retrieve Schema version (objectVersion) of LDAP server

### ISSUE THREAD

**Issue by gustavoluvizotto** [go-ldap/ldap#524]
Hi,

I've been looking for ways to retrieve the property value of an LDAP server by searching the Root DSE. However, the library does not provide such functionality. I'm looking specifically at the schema version (object version). In fact, I found only an AD client that can do it: https://support.globalsign.com/Certificate-Automation-Manager/how-check-active-directory-schema-version

Any pointers on how to implement that? I tried to querying my local LDAP server with ldapsearch without success.

Thank you!

**Comment by FlipB** [comment]
You can just search for the rootDSE properties, eg `ldap.NewSearchRequest("", ldap.ScopeBaseObject, ldap.NeverDerefAliases, 0, 0, false, "(&(objectClass=*))", []string{"dnsHostName"}, nil)` 

Not sure if there's an `objectVersion` though, going by https://learn.microsoft.com/en-us/windows/win32/adschema/rootdse

**Comment by cpuschma** [comment]
@gustavoluvizotto  You need to perform a search reques in the Configuration partition of your Active Directory:

For example:
```go
package ldap

import (
	"fmt"
	"github.com/go-ldap/ldap/v3"
)

func main() {
	conn, err := ldap.DialURL("ldap://example.com:389")
	if err != nil {
		// ...
	}
	defer conn.Close()

	conn.Bind("", "") // Authentication might be required, depending on your configuration
	searchResult, err := conn.Search(&ldap.SearchRequest{
		BaseDN:     "CN=Schema,CN=Configuration,DC=example,DC=com",
		Scope:      ScopeBaseObject,
		Filter:     "(objectClass=*)",
		Attributes: []string{"objectVersion"},
	})
	if err != nil {
		// ..
	}
	
	version := searchResult.Entries[0].GetAttributeValue("objectVersion")
	fmt.Printf("Schema Version is: %s\n", version)
}
```

**Comment by gustavoluvizotto** [comment]
Hi @cpuschma, sorry for this late response, I tested on that time and indeed the code you provided works.

What do you mean by the authentication might not be required? I could only do this by providing username and password.
