### ISSUE TITLE
how to set ldapsearch timeout?

### ISSUE THREAD

**Issue by fpawel** [go-ldap/ldap#528]
Could you please clarify how to CORRECTLY set the timeout for the `ldapsearch` operation. 

I see [SearchRequest.TimeLimit](https://github.com/go-ldap/ldap/blob/bc6bdd8fdaf43f1be891821039121282eb8dd43a/search.go#L419) . As far as I can tell, this option limits the maximum duration of `ldapsearch`, but it is not clear to me in what units this limitation works - seconds, milliseconds, nanoseconds?

**Comment by cpuschma** [comment]
Hi, the `TimeLimit` fields represents the maximum amount of time the server SHOULD use to calculate the result. See RFC 2251:
> **timelimit**: A timelimit that restricts the maximum time (in seconds) allowed for a search. A value of 0 in this field indicates that no client-requested timelimit restrictions are in effect for the search.

**Comment by fpawel** [comment]
@cpuschma  Thanks for your help!
