### ISSUE TITLE
The number of records returned does not match what is stored in AD

### ISSUE THREAD

**Issue by GZ91** [go-ldap/ldap#529]
The number of records returned does not match what is stored in AD

Using page-by-page retrieval of users from the directory I get only 3533 out of 7000. What could be the reason? 

Here is an example:
https://go.dev/play/p/d1oyhfb_-Ak

I tried changing the settings in Active Directory:

MaxPoolThreads                  8
MaxPercentDirSyncRequests                       0
MaxDatagramRecv                 8192
MaxReceiveBuffer                        10485760
InitRecvTimeout                 240
MaxConnections                  5000
MaxConnIdleTime                 900
MaxPageSize                     5000
MaxBatchReturnMessages                  0
MaxQueryDuration                        240
MaxDirSyncDuration                      0
MaxTempTableSize                        10000
MaxResultSetSize                        262144
MinResultSets                   0
MaxResultSetsPerConn                    0
MaxNotificationPerConn                  10
MaxValRange                     1500
MaxValRangeTransitive                   0
ThreadMemoryLimit                       10
SystemMemoryLimitPercent                        80

**Comment by cpuschma** [comment]
Can you describe how you get the number 7000? Can you describe what LDAP tool and most importantly what search filter you used in the other tool?
