### ISSUE TITLE
同步用户到ldap时候，将用户添加到部门内uniqueMember参数不支持

### ISSUE THREAD

**Issue by iyongfei** [go-ldap/ldap#532]
LDAP Result Code 65 "Object Class Violation": attribute 'uniqueMember' not allowed

/ AddUserToGroup 添加用户到分组
func (x GroupService) AddUserToGroup(dn, udn string) error {
	//判断dn是否以ou开头
	if dn[:3] == "ou=" {
		return errors.New("不能添加用户到OU组织单元")
	}
	newmr := ldap.NewModifyRequest(dn, nil)
	newmr.Add("uniqueMember", []string{udn})

	// 获取 LDAP 连接
	conn, err := common.GetLDAPConn()
	defer common.PutLADPConn(conn)
	if err != nil {
		return err
	}

	return conn.Modify(newmr)
}

**Comment by t2y** [comment]
To set `uniqueMember` attribute to a group entry, the entry must have `groupOfUniqueNames` in the objectClass. Confirm the entry's objectClass.

Next time, you can ask a question on GitHub discussions.

* https://github.com/orgs/go-ldap/discussions/categories/q-a

**Comment by johnweldon** [comment]
Thank you @t2y - I'll close this issue - feel free to continue asking questions in the discussions forum.
