### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [go-ldap/ldap#55]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for go-ldap and versioning would help Debian keep up with development.

**Comment by liggitt** [comment]
There are tags at https://github.com/go-ldap/ldap/tags

Were you referring to something else?

**Comment by aviau** [comment]
I should have noticed, sorry! I am opening bugs in many repositories so I may be going too fast :).

Thank you!
