### ISSUE TITLE
Bind returns nil

### ISSUE THREAD

**Issue by Cheeches** [go-ldap/ldap#61]
When i set the password parameter as an empty string the  

func (l *Conn) Bind(username, password string) error 

returns nil as error so that my users can login with username and empty password.

**Comment by liggitt** [comment]
can you run with debugging enabled? the only way I can see that returning nil is if the LDAP server returned an LDAPResultSuccess

**Comment by Cheeches** [comment]
Yes i get  int=0 (LDAPResultSucces) so it's a problem of the ldap administration?

**Comment by liggitt** [comment]
Yes, it sounds like your server is allowing unauthenticated binds

**Comment by Cheeches** [comment]
Thank you for the lib and your fast response
