### ISSUE TITLE
Support LDAP Unbind

### ISSUE THREAD

**Issue by sona-tar** [go-ldap/ldap#79]
Do you have a plan to support LDAP Unbind?

Now following sequese dosen't exec unbind but I want to unbind between 3 and 4.
1. dial
2. bind
3. search
4 bind
5. close

**Comment by vetinari** [comment]
Unbind means closing the connection. As soon as you bind again during a connection, the old bind is no longer in use (even if it fails usually).

**Comment by liggitt** [comment]
agree, no unbind is needed between step 3 and 4. if you want to revert to an anonymous state, you can do an anonymous simple bind (if your server supports it)

**Comment by sona-tar** [comment]
OK. I understood. Thanks.

RFC 4511 - Lightweight Directory Access Protocol (LDAP): The Protocol https://tools.ietf.org/html/rfc4511#section-4.3

>The function of the Unbind operation is to terminate an LDAP session.
   The Unbind operation is not the antithesis of the Bind operation as
   the name implies.  The naming of these operations are historical.
   The Unbind operation should be thought of as the "quit" operation.
