### ISSUE TITLE
DialTLS: use tls.Dial instead of doing an explicit handshake

### ISSUE THREAD

**Issue by ericchiang** [go-ldap/ldap#94]
This was brought up in https://github.com/coreos/dex/pull/689

Currently `DialTLS()` uses `net.Dial` then performs an explicit handshake.[0]

We noticed this because `tls.Dial` does a few other things like inferring the ServerName[1], but since the LDAP client doesn't use that code path, users have to set it explicitly.

Is there a reason this client needs to do its own handshake?

[0] https://github.com/go-ldap/ldap/blob/d0a5ced67b4dc310b9158d63a2c6f9c5ec13f105/conn.go#L124-L138
[1] https://github.com/golang/go/blob/go1.7.3/src/crypto/tls/tls.go#L134-L141

**Comment by liggitt** [comment]
https://github.com/go-ldap/ldap/pull/65/files switches to use DialWithDialer, but depends on a newer version of go. Will switch to that for 1.3 when we bump minimum supported go versions

**Comment by ericchiang** [comment]
cool, thanks.

**Comment by stefanmcshane** [comment]
Closing as this can be implementing using [DialWithDialer DialOpt](https://github.com/go-ldap/ldap/blob/685bfb34c8140f77e6283bab0dae10ea10c7a663/v3/conn.go#L120) with [DialURL](https://github.com/go-ldap/ldap/blob/685bfb34c8140f77e6283bab0dae10ea10c7a663/v3/conn.go#L199)
